### ISSUE TITLE
Chapter19: how to pass a base64 code for an image to predict ?

### ISSUE THREAD

**Issue by Schrominger** [ageron/handson-ml2#105]
Hi, thanks for the nice book.

 In chapter 19, the REST API input by transferring a numpy array to json format and sending to the API, but  I was wondering how could I do if I want to send a base64 for an image to preditct the model result rather than a numpy array?

Thanks for any possible tips !

**Comment by ageron** [comment]
Hi @Schrominger ,

Thanks for your question, and sorry for the late response. I'm really glad you're enjoying my book! :)

Here's a possible solution. On the client side:

```python
import tensorflow as tf
import json

paths = ["test1.jpg", "test2.jpg"]
image_data = [tf.io.read_file(path).numpy() for path in paths]
encoded_images = [tf.io.encode_base64(data).numpy().decode("ascii")
                  for data in image_data]

input_data_json = json.dumps({
    "signature_name": "serving_default",
    "instances": encoded_images,
})

And on the server side, you can decode each encoded string like this:

```python
import tensorflow as tf

def decode_image(data):
    return tf.io.decode_jpeg(tf.io.decode_base64(data))
```

Hope this helps.

**Comment by Schrominger** [comment]
> Hi @Schrominger ,
> 
> Thanks for your question, and sorry for the late response. I'm really glad you're enjoying my book! :)
> 
> Here's a possible solution. On the client side:
> 
> ```python
> import tensorflow as tf
> import json
> 
> paths = ["test1.jpg", "test2.jpg"]
> image_data = [tf.io.read_file(path).numpy() for path in paths]
> encoded_images = [tf.io.encode_base64(data).numpy().decode("ascii")
>                   for data in image_data]
> 
> input_data_json = json.dumps({
>     "signature_name": "serving_default",
>     "instances": encoded_images,
> })
> 
> And on the server side, you can decode each encoded string like this:
> 
> ```python
> import tensorflow as tf
> 
> def decode_image(data):
>     return tf.io.decode_jpeg(tf.io.decode_base64(data))
> ```
> 
> Hope this helps.

thx for your nice reply anyway!
