### ISSUE TITLE
Docker compose build failing

### ISSUE THREAD

**Issue by nebrass** [ageron/handson-ml2#107]
I just cloned the repository and tried to do a `docker-compose build`, I got this error:
```
Pip subprocess error:
    ERROR: Command errored out with exit status 1:
     command: /opt/conda/envs/tf2/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-jud7wcnr/avro-python3/setup.py'"'"'; __file__='"'"'/tmp/pip-install-jud7wcnr/avro-python3/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-jud7wcnr/avro-python3/pip-egg-info
         cwd: /tmp/pip-install-jud7wcnr/avro-python3/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-jud7wcnr/avro-python3/setup.py", line 41, in <module>
        import pycodestyle
    ModuleNotFoundError: No module named 'pycodestyle'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.


CondaEnvException: Pip failed

ERROR: Service 'handson-ml2' failed to build: The command '/bin/sh -c conda update -y -n base conda     && echo '    - pyvirtualdisplay' >> /tmp/environment.yml     && conda env create -f /tmp/environment.yml     && conda clean -y -t     && rm /tmp/environment.yml' returned a non-zero code: 1
```
As the error said, the `pycodestyle` package is not found 😭

**Comment by jvac06** [comment]
I tried to run `docker-compose build` too but got this error. Any thoughts for help?

`Step 2/18 : RUN apt-get update && apt-get upgrade -y     && apt-get install -y         libpq-dev         build-essential         git         sudo         cmake zlib1g-dev libjpeg-dev xvfb ffmpeg xorg-dev libboost-all-dev libsdl2-dev swig         unzip zip     && rm -rf /var/lib/apt/lists/*
 ---> Running in 4...
Get:1 http://security.debian.org/debian-security buster/updates InRelease [65.4 kB]
Get:2 http://deb.debian.org/debian buster InRelease [122 kB]
Get:3 http://deb.debian.org/debian buster-updates InRelease [49.3 kB]
Get:4 http://deb.debian.org/debian buster/main amd64 Packages [7907 kB]
Reading package lists...
E: Release file for http://security.debian.org/debian-security/dists/buster/updates/InRelease is not valid yet (invalid for another 1d 4h 17min 37s). Updates for this repository will not be applied.
E: Release file for http://deb.debian.org/debian/dists/buster-updates/InRelease is not valid yet (invalid for another 1d 6h 27min 20s). Updates for this repository will not be applied.
ERROR: Service 'handson-ml2' failed to build: The command '/bin/sh -c apt-get update && apt-get upgrade -y     && apt-get install -y         libpq-dev         build-essential         git         sudo         cmake zlib1g-dev libjpeg-dev xvfb ffmpeg xorg-dev libboost-all-dev libsdl2-dev swig         unzip zip     && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100`

**Comment by ageron** [comment]
Thanks for your feedback.
I updated the environment.yml file, hopefully things work better now? I just built the docker image (clone repo, then cd docker, and make build), it works fine for me. Could you please try again and tell me if it works for you as well?
If nothing else works, you can use the image I just built:

```bash
docker pull ageron/handson-ml2
```

Hope this helps.

**Comment by nebrass** [comment]
Yes it's fully working 😊 Merci !
This issue is closed..

**Comment by nebrass** [comment]
Yes it's fully working 😊 Merci !
This issue is closed..
