### ISSUE TITLE
[Chapter 14] AssertionError 

### ISSUE THREAD

**Issue by SBFallout** [ageron/handson-ml2#112]
Return error for executing following codes block:
    test_split, valid_split, train_split = tfds.Split.TRAIN.subsplit([10, 15, 75])

    test_set_raw = tfds.load("tf_flowers", split=test_split, as_supervised=True)
    valid_set_raw = tfds.load("tf_flowers", split=valid_split, as_supervised=True)
    train_set_raw = tfds.load("tf_flowers", split=train_split, as_supervised=True)

Details of error as follows:
    /usr/local/lib/python3.6/dist-packages/tensorflow_datasets/core/tfrecords_reader.py in 
    _str_to_relative_instruction(spec)
        277   res = _SUB_SPEC_RE.match(spec)
        278   if not res:
  --> 279     raise AssertionError('Unrecognized instruction format: %s' % spec)
        280   unit = '%' if res.group('from_pct') or res.group('to_pct') else 'abs'
        281   return ReadInstruction(

        AssertionError: Unrecognized instruction format: NamedSplit('train')(tfds.percent[0:10])

**Comment by LingLing40** [comment]
I also got that error. You could try this instead

`test_set = tfds.load("tf_flowers", split="train[:10%]", as_supervised=True) `
`valid_set = tfds.load("tf_flowers", split="train[10%:25%]", as_supervised=True)`
`train_set = tfds.load("tf_flowers", split="train[25%:]", as_supervised=True)`

**Comment by ageron** [comment]
Thanks for your question, @SBFallout . Indeed, TFDS updated its Split API (called S3 now), so the new way to split datasets is as shown by @LingLing40 (thanks!). I updated the notebook (and the book).
