### ISSUE TITLE
[Chapter 3, 2019-11-22: Third Release version] Page 98 Line 7 from bottom 

### ISSUE THREAD

**Issue by hbunyamin** [ageron/handson-ml2#118]
Dear Mr. Geron,

The sentence:
"In contrast, the PR curve makes it clear that the classifier has room for improvement (the curve could be closer to the top-left corner)."

I suggest it should be:
"In contrast, the PR curve makes it clear that the classifier has room for improvement (the curve could be closer to the **top-right corner**)." because the closer the PR curve to the top-right corner, the better the classifier is.

Correct me if I am wrong. Thank you.

**Comment by ageron** [comment]
Hi @hbunyamin ,
Great catch, thanks! Indeed, it should say "top-right corner". I fixed this in the fourth release which came out a couple weeks ago.
Hope you're enjoying the rest of the book!
