### ISSUE TITLE
[Chapter 10] Multiple inputs should be provided as list, not tuple

### ISSUE THREAD

**Issue by Lorenzo-Giardi** [ageron/handson-ml2#119]
Hello, 
in the notebook `10_neural_nets_with_keras.ipynb`, in the part related to NN with multiple inputs (code chunk 59), those are provided to the keras fit method as a tuple, which results in `AttributeError: 'tuple' object has no attribute 'ndim'`. 

```
history = model.fit((X_train_A, X_train_B), y_train, epochs=20,
                    validation_data=((X_valid_A, X_valid_B),  y_valid))
mse_test = model.evaluate((X_test_A, X_test_B), y_test)
y_pred = model.predict((X_new_A, X_new_B))
```
Fix:
```
history = model.fit([X_train_A, X_train_B], y_train, epochs=20,
                    validation_data=([X_valid_A, X_valid_B], y_valid))
mse_test = model.evaluate([X_test_A, X_test_B], y_test)
y_pred = model.predict([X_new_A, X_new_B])
```
By the way, your book (2nd edition) is really good, thank you!

**Comment by ageron** [comment]
Hi @Lorenzo-Giardi ,

Thanks for your feedback, and my apologies for the late response. Unfortunately, I cannot reproduce this error: [the Colab](https://colab.research.google.com/github/ageron/handson-ml2/blob/master/10_neural_nets_with_keras.ipynb) runs without any issue (apart from an unrelated issue in cell 100).
May I ask you what version of TensorFlow and Keras you are using?

**Comment by Lorenzo-Giardi** [comment]
All right, I found why: providing multiple inputs using a tuple works fine with **tf.keras** (at least the version in colab), but doesn't work with any standalone version of **Keras** (I tried 2.2.5 and 2.3.1). So, I would suggest switching to a list as it is perfectly compatible with both.
In fact, it is strange that the tuple even works in tf.keras given that both APIs documentations state that the input should be provided as: 
> a Numpy array (or array-like), or a list of arrays (in case the model has multiple inputs).

(by the way, I was using TensorFlow 2.1 and standalone Keras 2.2.5)

**Comment by ageron** [comment]
Thanks for your feedback @Lorenzo-Giardi , I'll update the notebooks and the book to use lists instead of tuples. 👍
