### ISSUE TITLE
Docker image scikit-learn out of date

### ISSUE THREAD

**Issue by GuillaumeQuenneville** [ageron/handson-ml2#12]
I created a fresh docker image. Book 1 code example 1-1 asserts sklearn >=.20 but the installed version is .19.1

Running make exec then conda update scikit-learn says user does not have write permissions to /opt/conda and sudoing the command says conda command not found.

**Comment by ageron** [comment]
Hi @GuillaumeQuenneville ,

Ah thanks. I just updated the docker image for the first edition. I'll update the 2nd edition as well (but it's a moving target right now, as TF 2.0 is not released yet, so I'm using nightly builds).
