### ISSUE TITLE
"KMeans instance preserves a copy of the labels of the instances it was trained on" (Ch. 9)

### ISSUE THREAD

**Issue by notestaff** [ageron/handson-ml2#130]
Given that `y_pred is kmeans.labels_` returns True, it's saving the original, not the copy?

**Comment by ageron** [comment]
Hi @notestaff ,
Good point, thanks. I fixed that sentence in the book. It now read: "The `KMeans` instance preservesthe labels of the instances it was trained on, available via the `labels_` instance variable". This will be included in the 5th release of the 2nd edition.
Thanks again!
