### ISSUE TITLE
Ch 14 Tackling Fashion MNIST with CNN error

### ISSUE THREAD

**Issue by nellmitchell** [ageron/handson-ml2#131]
I get the following error message when trying to fit the CNN sequential model for Fashion MNIST images (p461 of the book) using the code in the Github repository (https://colab.research.google.com/github/ageron/handson-ml2/blob/master/14_deep_computer_vision_with_cnns.ipynb)  (it's generated by code cell 30):

ValueError: Layer sequential expects 1 inputs, but it received 2 input tensors. Inputs received: [<tf.Tensor 'IteratorGetNext:0' shape=(None, 28, 28, 1) dtype=float32>, <tf.Tensor 'ExpandDims:0' shape=(None, 1) dtype=uint8>]

I didn't change any code, just ran it from the top - any idea what's wrong?

**Comment by sergiohgx** [comment]
This error started after Google Colab updated to Tensorflow 2.2.0-rc1...

**Comment by ageron** [comment]
Thanks a lot for your feedback. I'll update the notebooks to use tuples instead of lists, apparently it's a breaking change in TF 2.2.
