### ISSUE TITLE
[Chapter 15] Colab notebook hangs when trying to open

### ISSUE THREAD

**Issue by mpettis** [ageron/handson-ml2#135]
Doing a spot check, most notebooks open when I go to Colab and try to open them.  However, this one has been hanging, and will not open.  Not sure if it is just me, but as others open fine, I have to think it isn't.

https://colab.research.google.com/github/ageron/handson-ml2/blob/master/15_processing_sequences_using_rnns_and_cnns.ipynb

**Comment by mpettis** [comment]
I'm closing -- it opened, but this one took on the order of 10 minutes to open, vs. on the order of seconds for the other notebooks.

**Comment by ageron** [comment]
Thanks for your feedback. Yes, it seems that it's much larger than the others, I hadn't noticed. Perhaps the audio samples that get generated at the end are part of the notebook, I'll check.

**Comment by ageron** [comment]
Hi @mpettis,
I shrunk the <s>kids</s> notebook, it should be much faster to load in Colab, now.
Thanks again for your feedback. 👍
