### ISSUE TITLE
[Preface]  - Geoffrey Hinton's course no longer exists on Coursera

### ISSUE THREAD

**Issue by theimgclist** [ageron/handson-ml2#14]
Hi @ageron . The Neural Network course that was mentioned in the Resources section in the Preface was discontinued from Coursera. The same course is available [here](https://www.cs.toronto.edu/~hinton/coursera_lectures.html).

**Comment by ageron** [comment]
Thanks. I pointed to the new course:
https://www.coursera.org/learn/machine-learning/
