### ISSUE TITLE
Chapter 18 - Colab book gives error at 'env.step(1) # Fire' in section 'TF-Agents Environments'

### ISSUE THREAD

**Issue by vidyabhandary** [ageron/handson-ml2#140]
I ran the google colab book for Chapter 18, without any changes and I am getting an error at 

`> env.step(1) # Fire`

in section 

`> TF-Agents Environments`

The error is 

```
AttributeError                            Traceback (most recent call last)
<ipython-input-89-550e74cbba45> in <module>()
----> 1 env.step(1) # Fire

3 frames
/usr/local/lib/python3.6/dist-packages/tf_agents/environments/gym_wrapper.py in _step(self, action)
    196     # actions we have a numpy scalar (e.g array(2)) which is not hashable
    197     # in this case, we simply pull out the scalar value which will be hashable.
--> 198     action = action.item() if self._action_is_discrete else action
    199 
    200     # TODO(oars): Figure out how tuple or dict actions will be generated by the

AttributeError: 'int' object has no attribute 'item'
```

From stackoverflow it looks like the variable may have been changed. However the previous code is the following

```
env = suite_gym.load("Breakout-v4")
env
env.seed(42)
env.reset()
```
Could any of the above have caused this error to happen ?

**Comment by fabrizioit** [comment]
I have the same issue.
According the  comment action.items(), I have defined an array actions[0,1,2,3] and put inside brackets, env.step(actions[1]), it seems to work. Unfortunately I'm going out of memory creating a 'reply buffer'

**Comment by vidyabhandary** [comment]
I tried this - 

```
action = np.array(1, dtype=np.int32)
env.step(action) # Fire
```
This worked and I am able to render the breakout_plot correctly.

I am also going out of memory creating a replay buffer.

**Comment by JulesVerny** [comment]
Yes I also had this problem, and changing the action to a numpy array type got me through the first few preliminary review steps examples I have got into the main training loop without having to change any further code. 

I am running under Google CoLabs, and got this error, but I was able to restart with Additional RAM allocation, as prompted.

**Comment by iamrahul29** [comment]
import numpy as np
env.step(np.array(1))

Use this syntax.
The step() function now expects the argument to be Numpy Array

**Comment by jaehunchoe827** [comment]
I had the same issue and solved it thanks to the comments above!

For those who might face the same problem when running 
    `final_time_step, final_policy_state = watch_driver.run()`,

Replace this code 
    `tf_env.pyenv.envs[0].step(1)`
with 
    `tf_env.pyenv.envs[0].step(np.array(1))`.
 
Then the problem will be fixed.

% action = action.item() if self._action_is_discrete else action
% AttributeError: 'int' object has no attribute 'item'_

**Comment by jaehunchoe827** [comment]
I had the same issue and solved it thanks to the comments above.

For those who might face the same problem when running
`final_time_step, final_policy_state = watch_driver.run()`,

Replace this code
`tf_env.pyenv.envs[0].step(1)`
with
`tf_env.pyenv.envs[0].step(np.array(1))`.

Then the problem will be fixed.

% action = action.item() if self.action_is_discrete else action
% AttributeError: 'int' object has no attribute 'item'

**Comment by ageron** [comment]
This issue was fixed upstream by TF Agents, so you can use `.step(1)` instead of `.step(np.array(1))` now. Please upgrade to the latest version of TF Agents using:

```
pip install -U tf-agents
```
