### ISSUE TITLE
Chapter 03: sklearn.metrics.plot_confusion_matrix() available as of 0.22

### ISSUE THREAD

**Issue by genemishchenko** [ageron/handson-ml2#142]
Hi Aurelien!

It's not an "issue", but it may be helpful to include a comment for chapter 3 (classification) that as of version 0.22 sklearn has an in-built function for plotting confusion matrices - sklearn.metrics.plot_confusion_matrix() - that can be used instead of matplotlib.pyplot.imshow().

Cheers!
Gene.

**Comment by ageron** [comment]
Thanks for the heads up, I'll add a comment in the notebook! :)
