### ISSUE TITLE
Chapter 2 - Custom Transformers 

### ISSUE THREAD

**Issue by Dseal95** [ageron/handson-ml2#150]
Hi, 

I recently bought your Hands-On Machine Learning textbook and I am really enjoying it - thanks for writing such a comprehensive book! I have a small question on the purpose of the following piece of code in Chapter 2:  
##-----------------------------------------------------------------------------------------------

from sklearn.base import BaseEstimator, TransformerMixin

--# column index
rooms_ix, bedrooms_ix, population_ix, households_ix = 3, 4, 5, 6

class CombinedAttributesAdder(BaseEstimator, TransformerMixin):
    def __init__(self, add_bedrooms_per_room = True): # no *args or **kargs
        self.add_bedrooms_per_room = add_bedrooms_per_room
    def fit(self, X, y=None):
        return self  # nothing else to do
    def transform(self, X):
        rooms_per_household = X[:, rooms_ix] / X[:, households_ix]
        population_per_household = X[:, population_ix] / X[:, households_ix]
        if self.add_bedrooms_per_room:
            bedrooms_per_room = X[:, bedrooms_ix] / X[:, rooms_ix]
            return np.c_[X, rooms_per_household, population_per_household,
                         bedrooms_per_room]
        else:
            return np.c_[X, rooms_per_household, population_per_household]

attr_adder = CombinedAttributesAdder(add_bedrooms_per_room=False)
housing_extra_attribs = attr_adder.transform(housing.values)

##-----------------------------------------------------------------------------------------------

I understand the class and what it is doing, however I do not really understand the explicit need for the code. It seems quite complex and i'm not sure If I have completely missed the purpose. 

For me, it is just a way of adding a new attribute to your feature set based on whether you want it or not. There are no parameters / conditions that it must meet to be created apart from a user input boolean condition. In the book it says that "you can add any hyper-parameter to gate any data preparation step that you are not 100% sure of" and that it is good for finding "combinations" of features but I can't really see why. 

Apologies for the worded question but if you are able to help me with this, that would be much appreciated.

Thanks.

**Comment by vasili111** [comment]
@Dseal95 In github of the previous edition of the book there is many information about custom transformers: https://github.com/ageron/handson-ml/issues?q=class+CombinedAttributesAdder

I think it needs more information in the book about that code and custom transformers in general.

**Comment by Dseal95** [comment]
@vasili111 Thanks for sharing that link, it was really helpful. 

I agree about the additional information but the QA forum seems to have done the trick. 

Thanks, 
Dan
