### ISSUE TITLE
Chapter 11 : Exercise 8

### ISSUE THREAD

**Issue by satya400** [ageron/handson-ml2#156]
Hi @ageron 

Cell 138 & 143 - shouldn't we add the AlphaDropout layer with in the for loop?

Thanks
Satya

**Comment by Rouizi** [comment]
In the book, the author added AlphaDropout for all hidden layers but it is ok to add the AlphaDropout layer only after the last layer. Indeed the author in the book said (p367):

>  Moreover,  many state-of-the-art architectures only use dropout after the last hidden layer, so you may want to try this if full dropout is too strong.

**Comment by ageron** [comment]
Thanks for your question @satya400 , and thanks @Rouizi for the correct answer.
Closing this issue.
