### ISSUE TITLE
Cells after cell no. 33 not found

### ISSUE THREAD

**Issue by rudresh-dixit** [ageron/handson-ml2#18]
cells after cell no. 33 are missing . Can you please fix this issue.
here's a screenshot of this
![Screenshot (43)](https://user-images.githubusercontent.com/50676900/60494732-f76eb580-9ccc-11e9-9473-2789b3e8b3b3.png)

**Comment by ageron** [comment]
Hi @rudresh-dixit ,
Thanks for your feedback. The Jupyter notebook is fine, it's a github rendering bug. I contacted support@github.com.
In the meantime, you can use the [jupyter.org viewer](https://nbviewer.jupyter.org/github/ageron/handson-ml2/blob/master/04_training_linear_models.ipynb), it works fine.
Or you can open the notebook using Colab. Or run it locally.
Hope this helps,
Aurélien
