### ISSUE TITLE
Chapter 2 - Page111 missing codes: cross validation using RandomForestRegressor()

### ISSUE THREAD

**Issue by bigcindy** [ageron/handson-ml2#194]
Page111 missing codes: cross validation using RandomForestRegressor()

**Comment by ageron** [comment]
Hi @bigcindy ,
The books contains this:

```python
>>> from sklearn.ensemble import RandomForestRegressor
>>> forest_reg = RandomForestRegressor()
>>> forest_reg.fit(housing_prepared, housing_labels)
>>> [...]
>>> forest_rmse
18603.515021376355
```

The ellipsis (`[...]`) implies that I left this part out on purpose. It's just identical to the cross validation we did for other models, so it would be boring to repeat it once more. In the book, I left out several repetitive or unimportant details, to keep the focus on the important parts of the code. If you're ever lost or you want to see every single detail, simply check out the Jupyter notebooks.

Hope this helps.
