### ISSUE TITLE
Chapter 2: ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

### ISSUE THREAD

**Issue by dhapolapankaj** [ageron/handson-ml2#195]
After running below code,

```
%matplotlib inline

import pandas as pd
import matplotlib.pyplot as plt

housing = pd.read_csv("data_set/housing.csv")
plt.show(housing.hist( bins=50, figsize=(20, 15)))
```

 After displaying 9 histograms, following error is displayed

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-15-494e36646861> in <module>
      5 
      6 housing = pd.read_csv("data_set/housing.csv")
----> 7 plt.show(housing.hist( bins=50, figsize=(20, 15)))

C:\ProgramData\Anaconda3\envs\ageron\lib\site-packages\matplotlib\pyplot.py in show(*args, **kw)
    270     """
    271     global _show
--> 272     return _show(*args, **kw)
    273 
    274 

C:\ProgramData\Anaconda3\envs\ageron\lib\site-packages\ipykernel\pylab\backend_inline.py in show(close, block)
     47         # only call close('all') if any to close
     48         # close triggers gc.collect, which can be slow
---> 49         if close and Gcf.get_all_fig_managers():
     50             matplotlib.pyplot.close('all')
     51 

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

Below are the screenshots

![image](https://user-images.githubusercontent.com/29034223/85952478-3dfdfb00-b987-11ea-9c65-9c273b4e010c.png)
![image](https://user-images.githubusercontent.com/29034223/85952485-4d7d4400-b987-11ea-87a2-e765c207ffb5.png)
![image](https://user-images.githubusercontent.com/29034223/85952495-5c63f680-b987-11ea-8c1e-6de0036bd4d5.png)

I'm using 
Anaconda version - 4.8.2
Python - 3.6
pandas                    1.0.5
matplotlib                3.2.2
jupyterlab                2.1.4

**Comment by ageron** [comment]
You should probably use `housing.hist(...)` instead of `plt.show(housing.hist(...))`.
More generally, if you get any error, I recommend trying to run exactly the code in the Jupyter notebooks, and if it works, compare that with the code you are running.
Hope this helps.
