### ISSUE TITLE
Missing output value in 03_classification

### ISSUE THREAD

**Issue by velaris1** [ageron/handson-ml2#2]
Hi,

This issue applies to Chapter 3's code sample (i.e.: 03_classification).

When calculating the desired threshold value for a precision >= 0.09, the following is done:

`threshold_90_precision = thresholds[np.argmax(precisions >= 0.90)]`

Right after this statement, the following is written:

`threshold_90_precision`

Correct me if I'm wrong, but I believe this was done in order to demonstrate that the threshold in question is equal to _7816.155523682526_ (note: _7813_ is used in the graph examples / shown in comments, so there's a disparity there).

**The issue is that the output is missing.**

Thanks,
Hussein Khalil

**Comment by ageron** [comment]
Hi @velaris1 ,
Good catch, thanks a lot! 👍 
Indeed, the comment says 7813, but it should be ~7816.
I'll fix this now, and add the missing outputs.
