### ISSUE TITLE
CH14 Implementing a ResNet-34 CNN Using Keras

### ISSUE THREAD

**Issue by seismonastic** [ageron/handson-ml2#20]
Hi Aurélien, it seems that this line `model.add(ResidualUnit(filters, strides=strides))` does not work. 
![image](https://user-images.githubusercontent.com/42301466/60784945-ae62a980-a183-11e9-9ab9-1b13f3a96566.png)

It should be `model.add(ResidualUnit(filters, strides))` instead.

**Comment by ageron** [comment]
Great tx a lot! I'm currently traveling, but when I get back (couple of weeks), I'll fix this.

**Comment by seismonastic** [comment]
Thanks for your reply Aurélien. Your code was right. It was my fault, I define `strides` as `stride` in the definition of ResidualUnit. For those who also encounter the same issue, please check your spelling of strides in this line, `def __init__(self, filters, strides=1, activation="relu", **kwargs):`
