### ISSUE TITLE
Chapter 14: page 616, AttributeError: 'Split' object has no attribute 'subsplit'

### ISSUE THREAD

**Issue by bigcindy** [ageron/handson-ml2#204]
run this code:

```python
test_split, valid_split, train_split = tfds.Split.TRAIN.subsplit([10, 15, 75])

test_set_raw = tfds.load("tf_flowers", split=test_split, as_supervised=True)
valid_set_raw = tfds.load("tf_flowers", split=valid_split, as_supervised=True)
train_set_raw = tfds.load("tf_flowers", split=train_split, as_supervised=True)`
```

Raises an error:

```
AttributeError: 'Split' object has no attribute 'subsplit'
```

ps: the version of TFDS is 3.1.0

**Comment by Rouizi** [comment]
Try using the [new API](https://www.tensorflow.org/datasets/splits):
```
test_split, valid_split, train_split = tfds.load(
    "tf_flowers",
    split=["train[:10%]", "train[10%:25%]", "train[25%:]"],
    as_supervised=True)
```

**Comment by ageron** [comment]
Thanks for your feedback @bigcindy .

You're using a more recent version of TFDS than existed when I wrote the book, and unfortunately this is a breaking change. You could roll back to an older version, but I recommend instead using the latest version and fixing the code to use the new API, as @Rouizi suggested.

I try to update the code in the notebooks regularly to fix such breaking changes, so when you run into an issue, please check the notebook for the most up to date code.

In this particular case, I added the following warning in the notebook for chapter 14 last year:

> **Warning**: TFDS's split API has evolved since the book was published. The new split API (called S3) is much simpler to use:
> 
> ```python
> test_set_raw, valid_set_raw, train_set_raw = tfds.load(
>     "tf_flowers",
>     split=["train[:10%]", "train[10%:25%]", "train[25%:]"],
>     as_supervised=True)
> ```

Hope this helps!

Closing the issue. Please reopen if the problem persists.
