### ISSUE TITLE
RNN Chapter

### ISSUE THREAD

**Issue by vvvkkk123** [ageron/handson-ml2#21]
I wonder if there is a typo in the 15_RNN code? When you are plotting the graphs in the time series example, you use the following function. Looks like the labels for Actual and Forecast should be swapped.

```python
def plot_multiple_forecasts(X, Y, Y_pred):
    n_steps = X.shape[1]
    ahead = Y.shape[1]
    plot_series(X[0, :, 0])
    plt.plot(np.arange(n_steps, n_steps + ahead), Y_pred[0, :, 0], "ro-", label="Actual")
    plt.plot(np.arange(n_steps, n_steps + ahead), Y[0, :, 0], "bx-", label="Forecast", markersize=10)
    plt.axis([0, n_steps + ahead, -1, 1])
    plt.legend(fontsize=14)
```

**Comment by ageron** [comment]
Hi @vvvkkk123,
Wow, great catch, thanks! Indeed, Actual and Forecast should be swapped. I'll do this today.
