### ISSUE TITLE
[Chapter 2] Error: "Module 'urllib' has no attribute 'request'" 

### ISSUE THREAD

**Issue by nguyenhaison1999** [ageron/handson-ml2#219]
For anyone who runs into this problem. 
Just add  `import urllib.request`.

**Comment by tawheedrony** [comment]
Thanks a lot

**Comment by ageron** [comment]
Thanks @nguyenhaison1999 . Older versions of Python would automatically import `urllib.request` when importing `urllib`, but it's not the case anymore, which is why it's now necessary to import `urllib.request` instead of `urllib`.
