### ISSUE TITLE
18 - Reinforcement learning - It won't learn Deep-Q-Network

### ISSUE THREAD

**Issue by vvvkkk123** [ageron/handson-ml2#22]
When I run the Deep-Q-Network in tensorflow 1.14, I need to disable tf.random.seed. Which is fine, but then the model becomes unstable. It doesn't learn. In fact, it gets worse after each episode. I ran it maybe 20 times, and only 2 of them learned. Any ideas?

**Comment by 8bitmp3** [comment]
Deep RL is not stable, takes ages to learn, and generally hard to reproduce, so maybe you should provide more details.

Have you run it with TF2 beta1 instead of 1.14? `!pip install tensorflow-gpu==2.0.0-beta1`

You may also want to install `gym` and rerun the notebook in Google Colab with GPU enabled to check if the agent is learning or not.

**Comment by vvvkkk123** [comment]
Thanks for your reply. That provides some relief. I was thinking I was doing something wrong.

I tried running it on 2.0, but it broke my cuDNN installation. Then I reinstalled cuDNN, but it didn't update the PATH, etc. It turned into a mess.  Then I had to revert back to 1.14. I don't want to risk it now since I use it for teaching.

I'll try running it for more episodes, but I doubt it will help. The rewards curve looks like it becomes less and less intelligent after 600 epochs.

**Comment by ageron** [comment]
Hi @vvvkkk123 ,
As @8bitmp3 pointed out (thanks at lot), Deep RL is hard. See this great [blog post by Alex Irpan](https://www.alexirpan.com/2018/02/14/rl-hard.html). In short: it takes a lot effort to make it work, and often just changing the random seed (or anything at all in the code) will break everything. It can be really frustrating. On the positive side, when it works, it's amazing.

Here's a small excerpt from chapter 18:

> As the researcher Andrej Karpathy put it: "[supervised learning] wants to work. [...] RL must be forced to work". You will need time, patience, perseverance and perhaps a bit of luck too. This is a major reason RL is not as widely adopted as regular Deep Learning (e.g., ConvNets).
