### ISSUE TITLE
Chapter 2

### ISSUE THREAD

**Issue by singhashish18** [ageron/handson-ml2#230]
hey i stuck in exercise 3 i have no idea about feature_importances

**Comment by XWilliamY** [comment]
If you go to the notebook on chapter 2, you'll see that suggested solutions have been implemented below what shows up in the book. https://github.com/ageron/handson-ml2/blob/master/02_end_to_end_machine_learning_project.ipynb

**Comment by Aliiiu** [comment]
pls I am stucked at trying to fit the LinAlg model. it is giving svd related error

**Comment by Chuly90** [comment]
In Chp2.Ex3 solution I see that we need to compute the feature_importances first (somehow) and later prepare the data and select the most important features. But how?? How do we compute the feature_importances without the prepared_data?
Or the answer is to first prepare the data without the features selection, then train a model, obtain the most important features (so now we have the feature_importances) AND THENN prepare the data AGAIN with the pipeline to select the most important features?
-- Please help
@XWilliamY @ageron

**Comment by ageron** [comment]
@Aliiiu, thanks for your feedback. Could you please try updating your code to the latest version (using `git pull`) and also update your libraries to the latest versions (using `pip install --upgrade -r requirements.txt` if you use pip, or `conda env remove -n tf2 --all` followed by `conda env create -f environment.yml` if you use Anaconda). If the problem persists, please open a new issue and provide more details about your error (including the full stacktrace and the exact code that is failing).

@Chuly90 Thanks for your question. To compute the feature importances, a simple solution is to use a Random Forest like we did in Chapter 2. Indeed, it requires a bit of data preparation. You can build a preprocessing pipeline for that purpose, then measure the feature importances, and lastly drop the unimportant features. There might be several iterations of data preparation until the data is good enough to train a good model: this is normal. Preparing good data is a big part of a Machine Learning project.

Hope this helps.
