### ISSUE TITLE
Chapter 2: Housing plots

### ISSUE THREAD

**Issue by TharaPR** [ageron/handson-ml2#231]
The axes are not correct in all of the California housing plots in handson-ml and handson-ml2 repositories. x-axis should be latitude and y-axis should be longitude.

**Comment by TharaPR** [comment]
For the simple reason that latitudes are represented horizontally and longitudes vertically. You can see any map or globe to find out this. At one point in chapter two, California png image is retrieved. If you observe this png file or other actual map of California, you can observe a slight difference especially on the border of the map on the top left hand side.

**Comment by sarajcev** [comment]
> For the simple reason that latitudes are represented horizontally and longitudes vertically. You can see any map or globe to find out this. At one point in chapter two, California png image is retrieved. If you observe this png file or other actual map of California, you can observe a slight difference especially on the border of the map on the top left hand side.

I'm afraid that is not true. Please take a look at the following [link](https://en.wikipedia.org/wiki/Geographic_coordinate_system). It is quite clear that the latitudes are defined by the y-axis (ordinate), and the longitudes with an x-axis (abscissa) in the planar projections. Latitudes are going from the Equator (0 degrees) to North (90 degrees) at the northern hemisphere; this is obviously a y-axis reference.

**Comment by TharaPR** [comment]
> > For the simple reason that latitudes are represented horizontally and longitudes vertically. You can see any map or globe to find out this. At one point in chapter two, California png image is retrieved. If you observe this png file or other actual map of California, you can observe a slight difference especially on the border of the map on the top left hand side.
> 
> I'm afraid that is not true. Please take a look at the following [link](https://en.wikipedia.org/wiki/Geographic_coordinate_system). It is quite clear that the latitudes are defined by the y-axis (ordinate), and the longitudes with an x-axis (abscissa) in the planar projections. Latitudes are going from the Equator (0 degrees) to North (90 degrees) at the northern hemisphere; this is obviously a y-axis reference.

I'm sorry that your response is not true. In the very link that you have shared, there is the picture of Equator and you can see that this does not go from 0 degrees to North. Equator spans the earth horizontally. There are tons of images in Google which shows the latitudes and longitudes and you can verify them.

**Comment by TharaPR** [comment]
> > For the simple reason that latitudes are represented horizontally and longitudes vertically. You can see any map or globe to find out this. At one point in chapter two, California png image is retrieved. If you observe this png file or other actual map of California, you can observe a slight difference especially on the border of the map on the top left hand side.
> 
> I'm afraid that is not true. Please take a look at the following [link](https://en.wikipedia.org/wiki/Geographic_coordinate_system). It is quite clear that the latitudes are defined by the y-axis (ordinate), and the longitudes with an x-axis (abscissa) in the planar projections. Latitudes are going from the Equator (0 degrees) to North (90 degrees) at the northern hemisphere; this is obviously a y-axis reference.
