### ISSUE TITLE
Cannot see any of the Code

### ISSUE THREAD

**Issue by AbirKar** [ageron/handson-ml2#238]
I was reading the book and following along with code over here. I can't see any of the code now. When I click on the code the page loads but the code doesn't show. 
![Screenshot 2020-08-27 at 7 24 57 PM](https://user-images.githubusercontent.com/67972614/91451634-3e3d4880-e89b-11ea-9008-5a10d68cdd0c.png)

**Comment by swargo98** [comment]
I am facing the same problem.

**Comment by marc-o95** [comment]
Same with me.

**Comment by AbirKar** [comment]
if you guys manage to solve it. please let me know. ill do the same.

**Comment by abdoulsn** [comment]
For me it worked, so pleas check add blockers (if you have one) or kind of cookies problems. Otherwise you can dowload it and save it as .ipynb note .txt

![ml2](https://user-images.githubusercontent.com/33933023/91634509-414a4d00-e9f1-11ea-93b9-cd06c4b35dd5.PNG)

1.
