### ISSUE TITLE
Docker building hangs forever

### ISSUE THREAD

**Issue by ShaunFChen** [ageron/handson-ml2#24]
Not sure if it is related to [this issue](https://github.com/conda/conda/issues/8197), but it didn't help by updating to latest conda, suggested in the post before they closed it. In `Step 5/32 : RUN conda install -y -c conda-forge pyopengl xgboost nbdime` I got:
```
Solving environment: ...working... failed with initial forzen solve. Retrying with flexible solve. 
``` 
and the script started to run several `Examining...`, `Comparing specs that have this dependency...`, `Finding shortest conflict path...` package by package, both CPU and RAM usage ran high. Try to let it check but did not end overnight. 

My working environment is MacOS 10.14.6, Mid-2018 macbook pro, conda version is **4.7.11** from _Miniconda,_ first priority channel is **conda-forge**. 

For some reasons, it turns out to pass the solving environment step when I change the image resource at the 1st line in **docker/Dockerfile** from `FROM continuumio/anaconda3:2019.03` to be `FROM continuumio/miniconda3:latest`. It might happen to any other user who didn't install Anaconda but Miniconda.

**Comment by qwertypo888** [comment]
I had the same problem and I was able to build the image by following your suggestions. However, it later complained about Matplotlib not found when I tried to run the notebooks inside the container. Did you have the same problem?

**Comment by ShaunFChen** [comment]
Hi @qwertypo888,

Thanks for your feedback, I kept searching for the reasons causing this issue and possible solution. My apologies for my previous comment, it was not enough to run the materials. Since following the same steps, I suggested check by `docker container ls`. If there's already a container named "handson-ml2", then do `docker rm -f handson-ml2` to clean the wrong one.

This issue seems to caused by both [conda](https://github.com/conda/conda/issues/9004) and [docker image](https://hub.docker.com/r/continuumio/anaconda3). According to the [thread](https://stackoverflow.com/questions/57518050/conda-install-and-update-do-not-work-also-solving-environment-get-errors) reported recently, the problem from conda was still pending to be fixed. Our problem was triggered by pulling packages from conda-forge, so conda hanged forever to solve the confliction. I ran the initial code to test the environment of the [docker image](https://github.com/ContinuumIO/docker-images/tree/edf1bc32629ae2ff046b3a1cd07a4a35c5715dd3/anaconda3) but I got:
```
$ docker pull continuumio/anaconda3:2019.03
$ docker run -i -t continuumio/anaconda3:2019.03 /bin/bash
$ python -V
Python 3.7.3
```

Many threads suggested creating a conda environment with python 3.6, but in this case, we need the base environment.

Overall, it works for me to downgrade by simply adding `RUN conda install -y python=3.6` in **docker/DockerFile** as the 2nd line (still pull `FROM continuumio/anaconda3:2019.03`.) All the packages ran well for me now.

**Comment by qwertypo888** [comment]
Hi@ShaunFChen,
Thanks for the suggestion, it seems to be working better. But it has problem importing "graphviz", for example the 3rd code block of notebook "06_decision_trees.jpynb". Does graphviz work in your case?

**Comment by ShaunFChen** [comment]
Yeah [graphviz need to be installed by conda](https://stackoverflow.com/questions/33433274/anaconda-graphviz-cant-import-after-installation). I guessed it can be fixed by adding `python-graphviz` in **docker/DockerFile** at well. Not sure if it is an independent issue from docker building.

Meanwhile, instead of re-install the container every time, we can [go inside the container with root permission](https://stackoverflow.com/questions/25845538/how-to-use-sudo-inside-a-docker-container) and run the installation manually. First, run the docker by `make run` as usual, and then open another session do:
```
$ docker exec -it -u root handson-ml2 bash
```
You supposed to log in the container and get something like `(base) root@7d52911ef9e4:/home/devel/handson-ml2#`, then run the conda installation command after that as:
```
(base) root@7d52911ef9e4:/home/devel/handson-ml2# conda install -c conda-forge python-graphviz
```

I just checked it fixed the issue in "06_decision_trees.jpynb", didn't go further to other notebooks yet.

**Comment by qwertypo888** [comment]
Great! 

I added `python-graphviz` to the end of the following line in Dockerfile: 
`RUN conda install -y -c conda-forge ... python-graphviz`
and now I can run through the "06_decision_tree.ipynb" notebook without issue.

The key is to use `python-graphviz`, not `graphviz` (that was really confusing).

@ShaunFChen, Thank you so much for the suggestions!

**Comment by ageron** [comment]
Hi everyone, thanks for your contributions. I fixed the Dockerfile a few months back, everything should work fine now. I just tried building an image, and it looks good. I pushed it to docker hub, so you should be able to run `docker pull ageron/handson-ml2:latest`. However, I won't be building those on a regular basis, so it's probably safer to build your own, or else it might be outdated.

Closing this issue, but feel free to re-open it if something is wrong.
Cheers!
