### ISSUE TITLE
Chapter 2 Stratification Code Not Working: Error in Data Type

### ISSUE THREAD

**Issue by trobacker** [ageron/handson-ml2#262]
I'm having trouble getting the stratification done. I'm referring to the `for` loop after the StratifiedShuffleSplit function call. I tried to work around it by looking at the issues. I found that you could also try the defined `train_test_split` function with the stratified argument but I came across the same error. In my final attempt to resolve this, I tried running the Jupyter notebook straight from here and I still get the error! Could someone help me resolve this? Part of the error is pasted below..

TypeError                                 Traceback (most recent call last)
<ipython-input-26-9730d791daa8> in <module>
      2 
      3 split = StratifiedShuffleSplit(n_splits=1, test_size=0.2, random_state=42)
----> 4 for train_index, test_index in split.split(housing, housing["income_cat"]):
      5     strat_train_set = housing.loc[train_index]
      6     strat_test_set = housing.loc[test_index]

...

TypeError: object of type 'CategoricalDtype' has no len()

Do I have to manually change the object type of the new "income_cat" variable in the data frame? Has the function usage changed?

**Comment by AlessandroMiola** [comment]
It seems to be related to sklearn version 0.20.1 according to https://github.com/ageron/handson-ml/issues/378.
Hope it helps!

**Comment by trobacker** [comment]
Ah, thank you! This is exactly what I was looking for. Thanks for your quick response, I truly appreciate it!

Best Wishes,
Thomas
