### ISSUE TITLE
Why is there a salamander on the cover ?

### ISSUE THREAD

**Issue by mlm-root** [ageron/handson-ml2#283]
Why is there a salamander on the cover ? :) 
Thanks

**Comment by Praful932** [comment]
@mlm-root You can find the answer on the last page :)

**Comment by mlm-root** [comment]
@Praful932 Can't find it :/ I have the french version. I know it's an existential question but it haunts me hahahaha

**Comment by 8bitmp3** [comment]
@mlm-root https://www.oreilly.com/content/a-short-history-of-the-oreilly-animals/ you may have seen this. it appears it has to do with this https://www.bbc.co.uk/news/science-environment-39642462

**Comment by mlm-root** [comment]
oh it comes from the publisher! I thought it was athor's choice.. Thanks for your answers! @8bitmp3 @Praful932
