### ISSUE TITLE
Solutions to Chapter 09 Exercises

### ISSUE THREAD

**Issue by sh-shmss** [ageron/handson-ml2#29]
Hi

The solutions for chapter 9 exercises (Unsupervised Learning Techniques) are not included in the notebook.

Thanks,

**Comment by vedhasp** [comment]
Hi @ageron, can I take this up?

**Comment by ageron** [comment]
Hi @vedhasp, that would be wonderful, thanks a lot!

**Comment by ageron** [comment]
I pushed the solutions a few weeks back. Closing this issue.
