### ISSUE TITLE
cant open file!

### ISSUE THREAD

**Issue by chaosolid** [ageron/handson-ml2#296]
Hi Guys,

I could not open file on Github for " handson-ml2/09_unsupervised_learning.ipynb "... Tried many times. 
Could you please let me know why? 

Regards,
Edward

**Comment by Praful932** [comment]
@chaosolid Hi, try opening in [collab](https://colab.research.google.com/github/ageron/handson-ml2/blob/master/)

**Comment by ageron** [comment]
Hi @chaosolid,

Github's notebook viewer sometimes fails to open large files (and it also displays some math equations incorrectly). Therefore, I prefer to open notebooks using Colab: it can open every notebook, and you can even run the code (even with a GPU or TPU if you need one)!

So I fully agree with @Praful932 👍
