### ISSUE TITLE
Chapter 3 - Classification - Titanic

### ISSUE THREAD

**Issue by velaris1** [ageron/handson-ml2#3]
This applies to _**Chapter 3 - Classification**_, more specifically the exercise for the **Titanic data set**.

When discussing ways to improve the results, the following is expressed:

> (...) try to convert numerical attributes to categorical attributes: for example, **different age groups had very different survival rates (see below), so it may help to create an age bucket category and use it instead of the age.** Similarly, it may be useful to have a special category for people traveling alone since only 30% of them survived (see below).

We then proceed to create an "AgeBucket" attribute:

`train_data["AgeBucket"] = train_data["Age"] // 15 * 15`
`train_data[["AgeBucket", "Survived"]].groupby(['AgeBucket']).mean()`

Remarks:

1) We are using `train_data` which didn't go through the pre-processing pipeline (see: `preprocess_pipeline`). I assume this would impact the results due to the missing age entries (see `train_data.info()`) - should `X_train(:, 0)` be used instead ?
2) I have difficulty understanding the _15 * 15_ comment - what is the intention ?
3) The creation of the age buckets seems to be missing. I was able to achieve something similar by using panda.cut: `train_data["AgeBucket"] = pd.cut(X_train[:, 0], bins=[0,15,30,45,60,75,100], labels=["0","15","30","45","60","75"])`

Thanks, I thoroughly enjoyed the exercise.

**Comment by tommyod** [comment]
Regarding points (2) and (3): The `//` does not indicate a comment (`#` does). The  `//` operator performs integer division, and integer division followed by multiplication creates the buckets. Run the following code to see this.

```python
import numpy as np
ages = np.arange(18, 100) 
ages // 15 * 15
```

**Comment by velaris1** [comment]
Thanks Tommy. My apologies, coming from a C++ / C# world my brain automatically thought of comments.

**Comment by ageron** [comment]
Thanks for your question @tommyod , and thanks for the answer @velaris1 . 👍 
Please close the issue if everything is clear now.

**Comment by velaris1** [comment]
(it's the other way around actually, Tommy answered :))

I believe the first part of the question is still valid:

"We are using train_data which didn't go through the pre-processing pipeline (see: preprocess_pipeline). I assume this would impact the results due to the missing age entries (see train_data.info()) - should X_train(:, 0) be used instead ?"

**Comment by ageron** [comment]
Oops, I read a bit too fast: thanks for your question @velaris1 , and thanks for the answer @tommyod  :)

Regarding the `AgeBucket` feature, my goal was just to show that it is an interesting feature to add, since there seems to be big differences in survival rate across the age buckets.  A good way to add this feature would be to create a custom transformer. The same goes for the `RelativesOnboard`. You would probably want to put this transformer after the `Imputer` in the pipeline, or you would have to make the transformer robust to missing values.

I hope this helps!

**Comment by velaris1** [comment]
Thanks for the explanations @ageron, I appreciate it. I'll go ahead and close the issue.
