### ISSUE TITLE
[Chapter 13] Text Vectorization and Bag of Words

### ISSUE THREAD

**Issue by Praful932** [ageron/handson-ml2#300]
In the last Imdb Exercise removing the bag of words layer ,
![image](https://user-images.githubusercontent.com/45713796/97291171-8ebb2d00-186f-11eb-9d26-d422c6e894ee.png)
gives this error

> ValueError: The last dimension of the inputs to `Dense` should be defined. Found `None`.

Can't the output of the Text Vec directly be passed onto the dense layer, since the number of tokens of every input is preprocessed to 50 features? Why does adding the bow layer does not trigger this error?

**Comment by ibeauregard** [comment]
![Capture d’écran, le 2020-10-27 à 15 55 06](https://user-images.githubusercontent.com/1441192/97355097-d096a400-186c-11eb-83cb-bb9d1dc53cfc.png)

I can't tell you why exactly, but TensorFlow is unable to infer the output shape of the `TextVectorization` layer (although we are able to infer (None, 50)). Consequently, if the model goes directly from the `TextVectorization` layer to the `Dense` layer, the last dimension of the inputs to `Dense` (which is the last dimension of the output from `TextVectorization`) is indeed unknown, hence the error you got.

**Comment by Praful932** [comment]
Thanks @ibeauregard, Since it's a preprocessing layer made subclassing the Layer class, Maybe adding the compute output shape method and the build would make keras infer the shape, which in this case is not required as such. I'll close the issue for now. Could you check this #295  one
