### ISSUE TITLE
[Chapter 18]Error when `from tf_agents.environments import suite_gym` in Colab

### ISSUE THREAD

**Issue by ko-i** [ageron/handson-ml2#308]
When I run these codes:
`from tf_agents.environments import suite_gym`
it comes an error say that:

> ---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> <ipython-input-68-f2131af790fa> in <module>()
> ----> 1 from tf_agents.environments import suite_gym
> /usr/local/lib/python3.6/dist-packages/tf_agents/environments/__init__.py in <module>()
>      17 
>      18 # TODO(b/155801943): Bring parallel_py_environment here once we're py3-only.
> ---> 19 from tf_agents.environments import batched_py_environment
>      20 from tf_agents.environments import py_environment
>      21 from tf_agents.environments import random_py_environment
> 
> /usr/local/lib/python3.6/dist-packages/tf_agents/environments/batched_py_environment.py in <module>()
>      33 import tensorflow as tf  # pylint: disable=g-explicit-tensorflow-version-import
>      34 
> ---> 35 from tf_agents.environments import py_environment
>      36 from tf_agents.trajectories import time_step as ts
>      37 from tf_agents.typing import types
> 
> /usr/local/lib/python3.6/dist-packages/tf_agents/environments/py_environment.py in <module>()
>      32 
>      33 from tf_agents.specs import array_spec
> ---> 34 from tf_agents.trajectories import time_step as ts
>      35 from tf_agents.typing import types
>      36 from tf_agents.utils import common
> 
> /usr/local/lib/python3.6/dist-packages/tf_agents/trajectories/__init__.py in <module>()
>      16 """Trajectories module."""
>      17 
> ---> 18 from tf_agents.trajectories import policy_step
>      19 from tf_agents.trajectories import time_step
>      20 from tf_agents.trajectories import trajectory
> 
> /usr/local/lib/python3.6/dist-packages/tf_agents/trajectories/policy_step.py in <module>()
>      23 import collections
>      24 from typing import NamedTuple, Optional, Union
> ---> 25 from tf_agents.typing import types
>      26 
>      27 
> 
> /usr/local/lib/python3.6/dist-packages/tf_agents/typing/types.py in <module>()
>      39 Array = np.ndarray   # pylint: disable=invalid-name
>      40 TensorOrArray = Union[Tensor, Array]
> ---> 41 Distribution = tfp.distributions.Distribution
>      42 
>      43 TensorSpec = tf.TypeSpec
> 
> /usr/local/lib/python3.6/dist-packages/tensorflow_probability/python/internal/lazy_loader.py in __getattr__(self, item)
>      55 
>      56   def __getattr__(self, item):
> ---> 57     module = self._load()
>      58     return getattr(module, item)
>      59 
> 
> /usr/local/lib/python3.6/dist-packages/tensorflow_probability/python/internal/lazy_loader.py in _load(self)
>      39     """Load the module and insert it into the parent's globals."""
>      40     if callable(self._on_first_access):
> ---> 41       self._on_first_access()
>      42       self._on_first_access = None
>      43     # Import the target module and insert it into the parent's namespace
> 
> /usr/local/lib/python3.6/dist-packages/tensorflow_probability/python/__init__.py in _ensure_tf_install()
>      63             present=tf.__version__))
>      64 
> ---> 65   if tf.config.experimental.tensor_float_32_execution_enabled():
>      66     # Must import here, because symbols get pruned to __all__.
>      67     import warnings  # pylint: disable=g-import-not-at-top
> 
> **AttributeError: module 'tensorflow.compat.v1.config.experimental' has no attribute 'tensor_float_32_execution_enabled'**

The environment i use is the default environment in Colab.
I found that not only my code but the source code in repo also have this error.
Has anyone else found that?

**Comment by jaehunchoe827** [comment]
I had the same issue.

If you are using the same setup code in GitHub, then you might have installed the nightly version of tf-agents.
However, It seems that tf-agents-nightly is not compatible with tf-2.x in this situation. 

1. Please go to the 3rd paragraph of "Set up" code. then you could see
`try:
    # %tensorflow_version only exists in Colab.
    %tensorflow_version 2.x
    !apt update && apt install -y libpq-dev libsdl2-dev swig xorg-dev xvfb
    !pip install -q -U tf-agents-nightly pyvirtualdisplay gym[atari]
    IS_COLAB = True
except Exception:
    IS_COLAB = False`.

2. replace this line
`    !pip install -q -U tf-agents-nightly pyvirtualdisplay gym[atari]`
with this
`    !pip install -q -U tf-agents pyvirtualdisplay gym[atari]`.

3. then the error could be fixed.

**Comment by jcatanza** [comment]
I tried uninstalling the tf-agents-nightly and installing tf-agents instead as jaehunchoe827 suggested above, but it didn't solve the problem. So as far as I'm concerned the issue is still open.
