### ISSUE TITLE
MemoryError: Unable to allocate 359. MiB for an array with shape (60000, 784) and data type float64

### ISSUE THREAD

**Issue by DJayDixit** [ageron/handson-ml2#309]
Hi Austin,
I am currently reading chapter 3 of your book and I am thoroughly enjoying it. In the SGDClassifier part and in the Implementing cross-validation Part I am getting memory error which I do not understand. I am literally writing the same code that you wrote in the book.

I am using the Windows operating system and I don't know if it is an os specific error. Any help will be appreciated

**Comment by Praful932** [comment]
@DJayDixit Try restarting the kernel

**Comment by ageron** [comment]
Hi @DJayDixit ,
Thanks for your feedback. Unfortunately, you're getting an out-of-memory error which simply means that your machine does not have enough RAM to hold the data. You can try closing as many programs as you can to free some RAM, and make sure all Jupyter kernels are shutdown, except for the one you're trying to run. You might also want to reboot your computer, and make sure there are few programs automatically started upon reboot. You can find other ways to free some RAM on Google. Perhaps there's one process holding a lot of RAM (for example, web browsers often take a huge amount of RAM, and software like Microsoft Office as well). Once you've freed up as much RAM as possible, if you still get the same error, then you might need to add more RAM to your computer. If you don't want to do that, then you can try working with less data. For example, you could truncate the MNIST dataset to use only 10,000 images in the training set, randomly selected from the original 60,000 images.

I hope this helps. I'm closing this issue as it is not a problem with the code, but a hardware limitation on your computer.
