### ISSUE TITLE
typo in chapter 1

### ISSUE THREAD

**Issue by joy586** [ageron/handson-ml2#31]
I'm just reading pdf version from ebooks.com.
Just find typo as below: 'Reinforcement Learning isag a very different beast.'
Which should be 'Reinforcement Learning is a very different beast'.

**Comment by ageron** [comment]
Oops, indeed, thanks for your feedback! I just fixed this typo, it's too late for the very first batch of printed copies (they're already printed), but there will be a second print batch in ~1 month.
Thanks again!
