### ISSUE TITLE
SketchRNN Dataset Features Doubt

### ISSUE THREAD

**Issue by Praful932** [ageron/handson-ml2#315]
There are three features in the SketchRNN dataset downloaded from [here](http://download.tensorflow.org/data/quickdraw_tutorial_dataset_v1.tar.gz), namely `shape, class_index, ink`, What do these features mean except for `class_index`? 
The shape parameter is usually of the shape `[n,3]` and ink ranges from `[small_negative_value,1.0]`

**Comment by ageron** [comment]
Each sketch is composed of multiple strokes. Each stroke is a sequence of n triples, hence the shape [n, 3]. The ink should be 0 or 1 depending on whether the pen is up or down. The format is described here:
https://github.com/hardmaru/sketch-rnn-datasets#stroke-3-vector-format

I'm not sure why there are small negative values.

**Comment by Praful932** [comment]
After looking through the `draw_sketch`  and the link you provided I think it has to do with the way the data is encoded, Instead of the absolute coordinates, the relative coordinates are stored so the `cummulative sum` and the small coordinates, as for the negative sign, the coords are in the 3rd quadrant **y is negative**, so while plotting we make it `+ve`. Makes sense now.

Thanks
