### ISSUE TITLE
Chapter3 - classification - GridSearchCV

### ISSUE THREAD

**Issue by ssuhas76** [ageron/handson-ml2#319]
Hello

I have a hard time understanding the GridSearchCV running time. I have understood the concept and how it runs but i am not sure why it is taking 30 mins for a single fit. Is there anyway this could be speed up? 

```
from sklearn.model_selection import GridSearchCV

param_grid = [{'weights':['uniform','distance'],'n_neighbors':[3,4,5]}]

knn_clf = KNeighborsClassifier()
grid_search = GridSearchCV(knn_clf,param_grid,cv=5,verbose=3,n_jobs=-1)
grid_search.fit(X_train,y_train)
```

**Comment by Praful932** [comment]
Hello @ssuhas76 , GridSearchCV tries all the parameter combination and for each combination it will train each model `5` times using different folds each time so here total fits would be `total_combinations * 5 = (2*3) * 5 = 30`

**Comment by ssuhas76** [comment]
> Hello @ssuhas76 , GridSearchCV tries all the parameter combination and for each combination it will train each model `5` times using different folds each time so here total fits would be `total_combinations * 5 = (2*3) * 5 = 30`

Dear @Praful932 ,

Many thanks for your reply. I get the combinations part. I wanted to check if there is any way the GridSearchCv running faster. In my PC it is taking around 30-35 mins per fit. which is almost 15 hours for the entire run. On what configuration is depending on?

**Comment by Praful932** [comment]
@ssuhas76 Since scikit does not support GPU :/, best you can do is try [tweaking ](https://stackoverflow.com/questions/32761556/python-scikit-learn-n-jobs)the `n_jobs` parameter or try running it in the cloud on better CPUs.

**Comment by N2Network** [comment]
> Many thanks for your reply. I get the combinations part. I wanted to check if there is any way the GridSearchCv running faster. In my PC it is taking around 30-35 mins per fit. which is almost 15 hours for the entire run. On what configuration is depending on?

Get a Ryzen 9 3950x processor. n_jobs=-1 to use all the cores

**Comment by snoor05** [comment]
Is i7 processor and 16 gb ram with intel graphics (basic) good enough configuration for a machine learning and data science work?

**Comment by N2Network** [comment]
> onfi

It's all relative to the amount of time you want to spend waiting for the process to run. Plug your CPU into this website - https://www.cpubenchmark.net/cpu.php?cpu=AMD+Ryzen+9+3950X&id=3598 it will give you an idea on its relative speed vs. cost of upgrading.
