### ISSUE TITLE
repeat() method on a Dataset

### ISSUE THREAD

**Issue by mlm-root** [ageron/handson-ml2#329]
Hello
I can't see the point of using the repeat() method without any argument. It means that the source dataset is repeated indefinitely. When and how does it stop ? I don't get it.
Thanks :)
Melvin

**Comment by ageron** [comment]
Hi @mlm-root , thanks for your question. It's not very useful, in general I agree that it should be avoided. It can sometimes be useful when you want the training loop to have control over the number of batches it handles per epoch. For example:

```python
import tensorflow as tf
ds = tf.data.Dataset.range(5).repeat()
for i, x in zip(range(8), ds):
    print(x)
```

outputs:

```
tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(3, shape=(), dtype=int64)
tf.Tensor(4, shape=(), dtype=int64)
tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(2, shape=(), dtype=int64)
```

**Comment by mlm-root** [comment]
Well, ok, I see. Thank you @ageron and thank you for your amazing work! Your book is awesome!
