### ISSUE TITLE
[chaper 11] The Layer.updates is deprecated.

### ISSUE THREAD

**Issue by eatPizza311** [ageron/handson-ml2#332]
The code `bn1.updates` will return a warning  and an empty list as below:
```
WARNING:tensorflow:From <ipython-input-38-3f3161b80a85>:1: Layer.updates (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.
Instructions for updating:
This property should not be used in TensorFlow 2.0, as updates are applied automatically.
[]
```
So this part of the book might no longer remain true.

**Comment by ageron** [comment]
Thanks @eatPizza311 , indeed `layers.updates` is not part of the external API anymore. I've updated the notebook to stop using it, and the book to skip that paragraph.
Hope you enjoy the book!
