### ISSUE TITLE
Chappter 12, Ragged Tensors! A possible typo.

### ISSUE THREAD

**Issue by kasrahabib** [ageron/handson-ml2#336]
@ageron,

Title (Other Data Structures), the part about RaggedTensors states that Ragged tensors represent static lists of tensors, where every tensor has the same shape and data type.
 
On the other hand, if you check TensorFlow's documentation
 it states that raggedTensors are tensors with non-uniform shapes, which indicates that RaggedTensors can hold tensors of different shapes.

Am I missing something or its a typo in the book?

Cheers,
Kasra

**Comment by ageron** [comment]
Hi @kasrahabib ,

Good catch, thanks! I mean "rank", not "shape".

I initially had much more details in chapter 12, but this chapter was getting way too long, so I cut out the part about special data structures in TensorFlow and I moved it to appendix F. That's where the details about ragged tensors are located now. But I also added a brief description of each data structure in chapter 12... unfortunately, it seems I wrote it a bit too fast. I'll fix this now! It should say:

> Ragged tensors represent lists of tensors, where all tensors must have the same rank and data type, but their sizes may vary along some dimensions (called _ragged dimensions_). The `tf.ragged` package contains operations for ragged tensors.

Here's the description in appendix F, after:

```python
>>> print(r)
<tf.RaggedTensor [[67, 97, 102, 233], [67, 111, 102, 102, 101, 101],
                  [99, 97, 102, 102, 232], [21654, 21857]]>
```

> A ragged tensor is a special kind of tensor that represents a list of arrays of different sizes. More generally, it is a tensor with one or more _ragged dimensions_, meaning dimensions whose slices may have different lengths. In the ragged tensor `r`, the second dimension is a ragged dimension. In all ragged tensors, the first dimension is always a regular dimension (also called a _uniform dimension_).

Thanks again! Closing this issue.

**Comment by kasrahabib** [comment]
@ageron You are the best!
