### ISSUE TITLE
Chapter 2, page 71

### ISSUE THREAD

**Issue by ACassoni** [ageron/handson-ml2#338]
At the end of the second paragraph of page 71 it says "We have preprocessing pipeline that takes the full housing data and applies the appropriate transformations to each column". Shouldn´t it be " that takes the TRAINING HOUSING DATA and applies..."?

This seems confusing if you think about Data leakage.

Thanks!

**Comment by Aliiiu** [comment]
pls if you don't mind asking for another related problem in this chapter and how you solved it.

I'm finding it difficult to fit the LinAlg model. it is giving svd related error

**Comment by ageron** [comment]
Thanks for your feedback @ACassoni , you are right, I meant to say "the entire training data". I'll make the change in the book.

@Aliiiu , if you are still experiencing this difficulty, please open a new issue and copy/paste the exact code you're running, and the stacktrace of the error you are getting.
