### ISSUE TITLE
Chapter 13 (French version) : §5.3.* missing corresponding handbook

### ISSUE THREAD

**Issue by lebaste77** [ageron/handson-ml2#347]
Hello,

I am using the French version of the book (ISBN 978-2-10-079006-1), and it seems that chapter 13 (i.e. chapter 5) differs from the original version (at least the handbook), as :  
- There is no reference to the **Standardization** class in the handbook (except in the exercise solution)
- The one-hot encoding is not implemented the same way (**tf.lookup.StaticVocabularyTable** in the book, and **tf.feature_column.categorical_column_with_vocabulary_list** and **tf.feature_column.indicator_column** in the handbook),
- Moreover, _bucketization_, _hash_bucket_, _numeric_column_ is not included/explained in the french version

In fact, 
- the whole **tf.feature_column** part is not explained in the french version of the book (even if the code is easily understandable), 
- the use of **tf.one_hot** and **tf.lookup**, in the handbook, is only seen in the exercise solutions (added recently : [link](https://github.com/ageron/handson-ml2/commit/ade72946e5b4d1b2000e8fed3add7e018c4a0078#diff-5ab107920ed0d26e798156c98abe1b2fea74eba0f7928ef57e7e820fbb744f1c )) but clearly explained in the french book,
- and finally, the usage of **tf.nn.embedding_lookup** seems to be mentionned only in the French book.

Is it a mistake ? or maybe it is the same for the original book ? or some of these differences are on purpose ? the **tf.feature_column** shall be now forgotten in favor of **tf.lookup** ?

Note : I am still in the process of reading the chapter 13 (5) so far, so I may be misunderstanding and/or there may be other differences within this chapter.

_Edit : I did not have to workaround the ["import tensorflow.train" bug](https://github.com/ageron/handson-ml2/commit/794a0d881902b428b4b5fb45920cd2bd18e3f28a#diff-5ab107920ed0d26e798156c98abe1b2fea74eba0f7928ef57e7e820fbb744f1c), it worked well for me_

**Comment by lebaste77** [comment]
Ok, I had not read the beginning of 13.3.3 (5.3.3), nevermind. I suggest that you should include the same comment as in the book in the handbook at cell 85, precising that Feature Column API may be replaced by the new API (lookup, one_hot). This would avoid other reactions like mine.

So far, only the TextVectorization Layer seems to be still experimental (i did not manage to include it in my model, got an AttributeError).

**Comment by ageron** [comment]
Thanks for your feedback @lebaste77 👍 , I'll add a note in the notebook. I hope you're enjoying the rest of the book.
