### ISSUE TITLE
chapter 7 - voting classifiers - code issue

### ISSUE THREAD

**Issue by ml-learner20** [ageron/handson-ml2#349]
Hi,
Below code is from chapter 7 voting classifier , I think its calculating the majority of heads, in that case the comparison shouldn't be for more than 0.5 ,like ((np.random.rand(10000, 10) >= heads_proba).astype(np.int32)

```python
heads_proba = 0.51
coin_tosses = (np.random.rand(10000, 10) < heads_proba).astype(np.int32)
cumulative_heads_ratio = np.cumsum(coin_tosses, axis=0) / np.arange(1, 10001).reshape(-1, 1)
```

Thankyou for an awesome book!

**Comment by ageron** [comment]
Hi, thanks for your kind words!
`np.random.rand(10000, 10)` returns random numbers uniformly distributed between 0.0 and 1.0. Each number has a 10% chance of being smaller than 0.1, right? And a 1% chance of being smaller than 0.01. And more generally, it has a probability p of being **smaller** than p. So we must use `<`, not `>`.
I hope this helps.
