### ISSUE TITLE
unable to load MNIST data using fetch_openml()

### ISSUE THREAD

**Issue by philbangayan** [ageron/handson-ml2#356]
I tried to run this line from the beginning of Chapter 3:
    mnist = fetch_openml('mnist_784', version=1)

and got this error:
    ValueError: Dataset mnist_784 with version 1 not found.

I tried removing the second parameter or changing the dataset name to 'MNIST original', but neither worked. I'm running sys 3.8.5 and sklearn 0.23.2. Anyone else having this problem?

**Comment by DavidHeavey** [comment]
Chapter 3:
I have an error at the same location.missing However, it does load as i get this ok
X, y = mnist["data"], mnist["target"]
X.shape
# (70000, 784)

 I cloned the book notebooks directly and doesnt work in the books notebooks, not just my own version, so not sure what i'm missing , all else workng to that point so cant see what import/instal is missing ? However, the following from the Jup Notebok is not working and returns a .....KeyError: 0

some_digit = X[0]
some_digit_image = some_digit.reshape(28, 28)
plt.imshow(some_digit_image, cmap=mpl.cm.binary)
plt.axis("off")

save_fig("some_digit_plot")
plt.show()

**Comment by philbangayan** [comment]
I found a workaround from another thread here titled "mnist dataset." ([link](https://github.com/ageron/handson-ml/issues/301#issuecomment-448871246))

The post suggests using these lines:
> from tensorflow.keras.datasets import mnist
> (X_train, y_train), (X_test, y_test) = mnist.load_data()

Note that this creates the training and testing sets (X_train, y_train, X_test, and y_test) rather than X and y as fetch_openml() does. So there will be changes in the rest of the MNIST section of the notebook.

**Comment by gjcasanova** [comment]
I had the same problem. You could use this:
mnist = fetch_openml('mnist_784', parser='auto')

**Comment by artyomvp1** [comment]
> I had the same problem. You could use this: mnist = fetch_openml('mnist_784', parser='auto')

doesnt work.

**Comment by tintinthedev** [comment]
Don't forget to check the spelling, guys (it happened to me)

**Comment by jaycarlton** [comment]
I'm getting a 404 error when using `mnist_784`, `MNIST original` and `data_id=554`. I can see the dataset at https://www.openml.org/search?type=data&status=active&id=554, but when I use the `fetch_openml()` function to get it, I get 
```
HTTPError                                 Traceback (most recent call last)
[/tmp/ipython-input-2188563538.py](https://localhost:8080/#) in <cell line: 0>()
----> 4 mnist = fetch_openml('mnist_784', version=1, as_frame=False)


12 frames
[/usr/lib/python3.11/urllib/request.py](https://localhost:8080/#) in http_error_default(self, req, fp, code, msg, hdrs)
    641 class HTTPDefaultErrorHandler(BaseHandler):
    642     def http_error_default(self, req, fp, code, msg, hdrs):
--> 643         raise HTTPError(req.full_url, code, msg, hdrs, fp)
    644 
    645 class HTTPRedirectHandler(BaseHandler):

HTTPError: HTTP Error 404: Not Found
```

**Comment by ageron** [comment]
Hi @jaycarlton ,

Thanks for your feedback. There's nothing wrong with the code, it looks like openml.org has some issues, I can't even download MNIST (or other datasets) on their website. Hopefully this will be resolved soon. In the meantime, you can use this code instead:

from collections import namedtuple
from torchvision import datasets, transforms
import numpy as np

mnist = datasets.MNIST(".", download=True, transform=transforms.PILToTensor())
X = np.stack([np.array(img) for img, _ in mnist]) / 255.0
y = np.array([str(label) for _, label in mnist])
X = X.reshape(-1, 28 * 28)
MNIST = namedtuple("MNIST", ["data", "target", "DESCR", "keys"])
mnist = MNIST(X, y, "Temporary hack", lambda: ("foo", "bar"))
