### ISSUE TITLE
Blas GEMM Launch Failed Error when running

### ISSUE THREAD

**Issue by JollyWanderer** [ageron/handson-ml2#357]
```python

from tf_agents.agents.dqn.dqn_agent import DqnAgent

train_step = tf.Variable(0)
update_period = 4 # run a training step every 4 collect steps
optimizer = tf.compat.v1.train.RMSPropOptimizer(learning_rate=2.5e-4, decay=0.95, momentum=0.0,
                                     epsilon=0.00001, centered=True)
epsilon_fn = keras.optimizers.schedules.PolynomialDecay(
    initial_learning_rate=1.0, # initial ε
    decay_steps=250000 // update_period, # <=> 1,000,000 ALE frames
    end_learning_rate=0.01) # final ε
agent = DqnAgent(tf_env.time_step_spec(),
                 tf_env.action_spec(),
                 q_network=q_net,
                 optimizer=optimizer,
                 target_update_period=2000, # <=> 32,000 ALE frames
                 td_errors_loss_fn=keras.losses.Huber(reduction="none"),
                 gamma=0.99, # discount factor
                 train_step_counter=train_step,
                 epsilon_greedy=lambda: epsilon_fn(train_step))
agent.initialize()_
```

I get the following error when I run this cell for chapter 18. 

> Blas GEMM launch failed : a.shape=(1, 3136), b.shape=(3136, 512), m=1, n=512, k=3136 [Op:MatMul]
>   In call to configurable 'DqnAgent' (<class 'tf_agents.agents.dqn.dqn_agent.DqnAgent'>)

All the other code in the section seems to run fine. Does anyone know why this is happening?

**Comment by Htnek** [comment]
I think that has to do with out of memory.

Try to add:
`gpus = tf.config.experimental.list_physical_devices('GPU')
if gpus:
  try:
    # Currently, memory growth needs to be the same across GPUs
    for gpu in gpus:
      tf.config.experimental.set_memory_growth(gpu, True)
    logical_gpus = tf.config.experimental.list_logical_devices('GPU')
    print(len(gpus), "Physical GPUs,", len(logical_gpus), "Logical GPUs")
  except RuntimeError as e:
    # Memory growth must be set before GPUs have been initialized
    print(e)`

**Comment by ageron** [comment]
Thanks for your feedback, @JollyWanderer , and thanks for your suggestion @Htnek.

Also, I've recently updated all the libraries to the latest versions (including TF 2.4 and TF Agents 0.7). Perhaps try updating to these latest libraries and the latest code (I made minor tweaks)?

**Comment by lebaste77** [comment]
This could also happen when your GPU is already used by another process (I had this a couple of times too).

**Comment by ageron** [comment]
Indeed, thanks @lebaste77 that's a great point. 👍 
@JollyWanderer, please make sure you don't have another Jupyter notebook (or any other process) open with TensorFlow loaded, or else it will already have reserved most of the GPU's RAM. In chapter 19, this can easily happen since we import tensorflow and then we run some other processes (like tensorflow serving) that may also reserve RAM.

**Comment by JollyWanderer** [comment]
I see! Thank you guys for the input. I realized that I had a separate software that was using the GPU when I was running the algorithm. The code that @Htnek help as well! Thank you!
