### ISSUE TITLE
Appendix code

### ISSUE THREAD

**Issue by zechzhao** [ageron/handson-ml2#363]
Hi Ageron,

Could you please release notebook for appendices?

Thanks

**Comment by ageron** [comment]
Hi, thanks for your question.

* **Appendix A – Exercise Solutions**: the solutions to the code exercises are available at the end of each chapter's notebook.
* **Appendix B – Machine Learning Project Checklist**: there is no code in this appendix, but the checklist is available at https://github.com/ageron/handson-ml/blob/master/ml-project-checklist.md
* **Appendix C – SVM Dual Problem**: there is no code in this appendix, it's mostly maths. A PDF containing all of the book's equations is available at https://github.com/ageron/handson-ml2/blob/master/book_equations.pdf
* **Appendix D – Autodiff**: the code (and more) is available at https://github.com/ageron/handson-ml2/blob/master/extra_autodiff.ipynb
* **Appendix E – Other Popular ANN Architectures**: there is no code in this appendix. But there's a bit of maths. As explained above, you can view all the book's equations at https://github.com/ageron/handson-ml2/blob/master/book_equations.pdf
* **Appendix F – Special Data Structures**: this is actually part of the [notebook for Chapter 12](https://github.com/ageron/handson-ml2/blob/master/12_custom_models_and_training_with_tensorflow.ipynb). In fact, this whole appendix was initially part of chapter 12, but the chapter was very long and a bit boring, so I pulled out this part and put it in an appendix. :)
* **Appendix G – TensorFlow Graphs**: this is also part of the [notebook for Chapter 12](https://github.com/ageron/handson-ml2/blob/master/12_custom_models_and_training_with_tensorflow.ipynb). Again, this appendix used to be part of Chapter 12. You can imagine how long and boring this chapter was, it could even put to sleep caffeine addicts in under 5 minutes.

Hope this helps!

**Comment by zechzhao** [comment]
Thanks for the reply.
