### ISSUE TITLE
Is there a plan for a video course based on Hands-on ML?

### ISSUE THREAD

**Issue by minertom** [ageron/handson-ml2#367]
I would very much like to see the author doing a "run through" of this book and some of the concepts therein.

Regards
Tom

**Comment by ageron** [comment]
Thanks for your interest. I wanted to post plenty of videos on my YouTube channel (https://youtube.com/c/aureliengeron) but I quickly ran out of time. I still hope to upload videos one day, but frankly I'm not sure when. I'm closing this issue as I'll tweet whenever I upload a video. You can follow me at https://twitter.com/aureliengeron
