### ISSUE TITLE
cannot import name OrdinalEncoder in chapter 2

### ISSUE THREAD

**Issue by kumarUjjawal** [ageron/handson-ml2#37]
![Screen Shot 2019-10-01 at 9 36 06 PM](https://user-images.githubusercontent.com/10569915/65979788-89848680-e493-11e9-9bf0-f9babd7aeeae.png)

**Comment by kumarUjjawal** [comment]
Fixed it by using `from sklearn.preprocessing import LabelEncoder`

**Comment by ageron** [comment]
Hi @kumarUjjawal ,
It's nice that you found a workaround, but I would recommend you update your version of Scikit-Learn to the latest version, for example:

```bash
pip install -U sklearn
```

And restart python or Jupyter.

Hope this helps.
