### ISSUE TITLE
A suggestion for chapter 2 python code

### ISSUE THREAD

**Issue by d5423197** [ageron/handson-ml2#373]
plt.imshow(california_img, extent=[-124.55, -113.80, 32.45, 42.05], alpha=0.5,
           cmap=plt.get_cmap("jet"))

for this part of code, I would recommend you to change the "extent" to list(ax.get_xlim()) + list(ax.get_ylim()).

I was confused about how you get those numbers for "extent". I am not sure if other people would have the same doubts. 

Just a kind suggestion here.

**Comment by ageron** [comment]
Thanks for the kind suggestion. 👍 
I initially tried to use `ax.get_xlim()` and `ax.get_ylim()` to define the `extent` argument, but the result was slightly off, so I manually tweaked it until the image looked good. This is why the extent is hard-coded this way.

Notice that:

```python-shell
>>> list(ax.get_xlim()) + list(ax.get_ylim())
[-124.85199999999999, -113.808, 32.0695, 42.420500000000004]
```

which is not exactly equal to `[-124.55, -113.80, 32.45, 42.05]`.

Thanks again, though!
