### ISSUE TITLE
Google Cloud Platform: AI Predictions: response body 

### ISSUE THREAD

**Issue by melvin-lm** [ageron/handson-ml2#379]
Hello 

I created 2 models and I am wondering why do I get different response body when calling REST API?
To be more specific, in the first case, I get 2 dictionaries (keys: "predictions" and "dense_1", The latter is the output layer name of my model). In the second case, I get 1 dictionary (key:  "predictions"). This is weird because I am using the exact same model from GCS. The only difference between those 2 models is that the second one has a region endpoint in Europe and they don't run on same machine type (but I don't think there is a link with my issue). 

Case 1: `{'predictions': [{'dense_1': [9.130606807519459e-23, 4.872276949885089e-23, 0.002939987927675247, 0.957423210144043, 0.0, 7.103511528994133e-11, 6.0420668887672946e-05, 0.039576299488544464, 3.989315388447379e-12, 8.409963248741903e-32]}]}`

Case 2: `{'predictions': [[9.13060681e-23, 4.87227695e-23, 0.00293998793, 0.95742321, 0.0, 7.10351153e-11, 6.04206689e-05, 0.0395763, 3.98931539e-12, 8.40996325e-32]]}`

If someone has an idea? It is not a big deal but still I'd like to know.
Thks

**Comment by ageron** [comment]
Yikes, I've never seen this before. I'm guessing there's a different version of TF Serving running in these regions? I recommend contacting GCP for more details on this problem.

**Comment by melvin-lm** [comment]
Thank you for your feedback!

I got the same answer on stackoverflow https://stackoverflow.com/questions/66060254/google-cloud-platform-ai-platform-why-do-i-get-different-response-body-when-c/66242420#66242420

--> An issue has been reported to Google https://issuetracker.google.com/issues/180485182
