### ISSUE TITLE
In extra_autodiff d2f implementation problem 

### ISSUE THREAD

**Issue by AirChen** [ageron/handson-ml2#399]
In "Numeric differentiation" part, the  d2f func 

`def d2f(x, y):
    return [gradients(dfdx, [3., 4.]), gradients(dfdy, [3., 4.])]`

maybe changed to 

`def d2f(x, y):
    return [gradients(dfdx, [x, y]), gradients(dfdy, [x, y])]`

**Comment by ageron** [comment]
Good catch, thanks. Fixed.
