### ISSUE TITLE
Tensorflow v 2.0 seems to be incompatible with standalone Keras

### ISSUE THREAD

**Issue by Amanda-Clark** [ageron/handson-ml2#4]
I'm working my way through Ch 10, and I decided to follow along by using the standalone Keras API rather than Tensorflow's. I had TF updated to 2.0 as in the book, and when I changed the import statements to reflect that, I got this error.
https://github.com/keras-team/keras/issues/12379
The solutions they have are to downgrade to 1.1 something TF, or to use TF's built in Keras support. But it looks like using the standalone Keras with TF2 won't work as of right now.

**Comment by ageron** [comment]
Hi @Amanda-Clark ,
Thanks for your feedback. Indeed, Keras standalone has not been updated yet to support TF 2.0. I expect this will be resolved by the time the 2nd edition of my book is released, but I added a note in chapter 10 for readers of the early release. Thank you!
