### ISSUE TITLE
[BUG] (06_decision_trees.ipynb) Wrong random_state value undermining example

### ISSUE THREAD

**Issue by rynkk** [ageron/handson-ml2#422]
Hi,

in the "06_decision_trees.ipynb" notebook in cell 8 you are using the value **40** instead of the always used **42** for `random_state`.
If you change it to the correct value and train again, you will realize that the decision boundaries are actually identical for the tweaked AND the base IRIS-dataset.

So you are simply showing the stochastic nature of the underlying algorithm, not the sensitivity to training set details.

Reproducable with the [Google Colab notebook](https://colab.research.google.com/github/ageron/handson-ml2/blob/master/06_decision_trees.ipynb#scrollTo=5pFNwMlWnoO2) 

What it looks like with the correct `random_state`:
![Decision Boundaries with random_state=42](https://user-images.githubusercontent.com/35176649/116727751-43800380-a9e5-11eb-981c-5df83fa4d2c8.png)

**Comment by ageron** [comment]
Hi @rynkk,

Good catch! Changing both random states to 44 instead of 42 fixes the issue, I'll push this change.

Thanks!

**Comment by ageron** [comment]
You're right, this example illustrates the instability due to the stochastic & greedy nature of the algorithm, but it does not illustrate the point I was trying to make. In fact, the previous example already illustrates the sensitivity to small changes in the dataset (rotating the data completely changes the model), so adding another example is redundant. I'll rewrite this paragraph to highlight the instability due to the combination of randomness + greediness.

**Comment by ageron** [comment]
I've rewritten the paragraph like this:

> More generally, the main issue with Decision Trees is that they have a high variance: small changes may produce very different models. In fact, since the training algorithm used by Scikit-Learn is stochastic, even retraining the same Decision Tree on the exact same data may produce a very different model, such as the one represented in Figure 6-8 (unless you set the `random_state` hyperparameter). As you can see, it looks very different from the previous Decision Tree (Figure 6-2).


I also changed the title of Figure 6-8:

> Retraining the same model on the same data may produce a very different model

I'll clarify this in the notebook as well.

**Comment by ageron** [comment]
Thanks a lot for your contribution, @rynkk ! 👍

**Comment by rynkk** [comment]
Glad I was able to help!
