### ISSUE TITLE
[QUESTION] Chapter 9, In 105 : indexing question

### ISSUE THREAD

**Issue by popaconsta** [ageron/handson-ml2#428]
It's not clear to me why the indexing is done this way and why `np.arange(len(X_train))` can't be replaced with `:`? Or at least, that's what I would have done to select all the rows, and then, select particular columns.
It's clear to me what the code does, but I wasn't expecting this particular indexing method and I can't understand why it's needed instead of `:`. 

```python
X_cluster_dist = X_digits_dist[np.arange(len(X_train)), kmeans.labels_]
```

**Comment by ageron** [comment]
Hi @popaconsta ,

Good question! Let's compare the two:

```python
>>> X_cluster_dist = X_digits_dist[np.arange(len(X_train)), kmeans.labels_]
>>> X_cluster_dist.shape
(1347,)
>>> X_cluster_dist2 = X_digits_dist[:, kmeans.labels_]
>>> X_cluster_dist2.shape
(1347, 1347)
```

As you can see, the results are different, the first one returns a 1D array of length 1347, while the second one returns a 2D array of shape 1347x1347.

In the first case, we use [advanced NumPy indexing](https://numpy.org/doc/stable/reference/arrays.indexing.html#advanced-indexing) to retrieve specific values from `X_digits_dist`. The syntax is `a[[row1, row2, ..., row_n], [col1, col2, ..., col_n]]`, which returns a 1D array containing the values `a[row1, col1]`, `a[row2, col2]`, ..., `a[row_n, col_n]`.

In the second case, we're saying "for each row, give me the values in columns col1, col2, ..., col_n". It's basically an array that contains `a[0, cols]`, `a[1, cols]`, ..., `a[n-1, cols]`, where each `a[i, cols]` is itself a 1D array containing `a[i, col1]`, `a[i, col2]`, ..., `a[i, col_n]`.

I hope this is clearer?

If not, I suggest you play around with NumPy indexing a bit, it's very powerful but it can be a bit confusing. For example, create a simple array like this, and play with it:

```python
>>> a = np.array([[1,2,3], [4,5,6]])
>>> a[[0, 1, 0], [1, 1, 2]]
array([2, 5, 3])
>>> a[:, [1,1,2]]
array([[2, 2, 3],
       [5, 5, 6]])
```

Hope this helps!

**Comment by popaconsta** [comment]
Thank you @ageron for the detailed explanation. That made it clear indeed :)
