### ISSUE TITLE
[BUG] unable to load MNIST data through `fetch_openml` / unable to use this data when loaded through `tf`

### ISSUE THREAD

**Issue by zadrozny** [ageron/handson-ml2#433]
This issue has been reported, but I don't see a solution that's current.
 
Running 03_classification.ipynb, `mnist = fetch_openml('mnist_784', version=1, as_frame=False)` produces `OpenMLError: Dataset mnist_784 with version 1 not found.`

I have downloaded mnist.zip, inside of which there are four .gz files. What's the appropriate way to use them with the chapter code?

I've also tried `mnist = tf.keras.datasets.mnist.load_data(path="mnist.npz")` but this produces an tuple; running `mnist.keys()` yields: 

AttributeError: 'tuple' object has no attribute 'keys' 

Please help. I would like to work through Chapter 3.

**Comment by ageron** [comment]
Hi @zadrozny ,
Thanks for your feedback. Unfortunately, I cannot reproduce this issue. I ran the code `mnist = fetch_openml('mnist_784', version=1, as_frame=False)` on my MacBook, running Scikit-Learn 0.24.1, and it worked fine. I also created this [Colab Notebook](https://colab.research.google.com/drive/1tQV4wUwh8-NTAlCGdecVJD8HuXptciz-?usp=sharing) which runs fine.

So I'm really not sure what's going on. Perhaps there was a temporary problem with OpenML.org? Could you please try again? Or perhaps you need to upgrade Scikit-Learn? Which version are you running?

**Comment by zadrozny** [comment]
Indeed, I think the problem was OpenML.org. It's working now. Thank you. Enjoying the book.
