### ISSUE TITLE
Please give a complete example of RNN with attention(build model, compile model, fit model, predict)

### ISSUE THREAD

**Issue by thopv133802** [ageron/handson-ml2#45]
Please give a complete example of RNN with attention(build model, compile model, fit model, predict)

**Comment by ageron** [comment]
Hi @thopv133802 ,
Thanks for your question. Did you check out the section on attention mechanisms in chapter 16, page 549? It completes the code example on page 545 with a couple lines of code to add Luong attention to the model. I didn't want to copy/paste 20 lines of code just to add 2 lines, I hope this makes sense. Did you try this code, with the 2 extra lines? Did it fail? If so, could you please post the error?

If you want, you can also check out the [seq2seq section in TF Addons](https://github.com/tensorflow/addons/tree/master/tensorflow_addons/seq2seq), they have plenty of code examples there as well.

**Comment by thopv133802** [comment]
Sorry. Because when I concatenate your code. I have some issue but I can't resolve myself. Can you check the following code for me ?

Issue: tensorflow.python.framework.errors_impl.OperatorNotAllowedInGraphError: using a `tf.Tensor` as a Python `bool` is not allowed in Graph execution. Use Eager execution or decorate this function with @tf.function. 
I guess: de_output, _, _ = decoder(de_input_embedding_layer, sequence_length = de_sequences_length_layer, initial_state = decoder_cell.get_initial_state(dtype = tensorflow.float32, batch_size = tensorflow.constant(BATCH_SIZE))) cause this issue.

import re
import unicodedata
import numpy
import tensorflow
from matplotlib import pyplot
from keras_preprocessing.sequence import pad_sequences
from keras_preprocessing.text import Tokenizer
from tensorflow_addons.seq2seq import BasicDecoder, TrainingSampler, BeamSearchDecoder, tile_batch, LuongAttention, \
    AttentionWrapper
from tensorflow_core.python.keras.activations import softmax
from tensorflow_core.python.keras.engine.input_layer import Input
from tensorflow_core.python.keras.layers.core import Dense
from tensorflow_core.python.keras.layers.embeddings import Embedding
from tensorflow_core.python.keras.layers.recurrent import LSTM, LSTMCell
from tensorflow_core.python.keras.models import Model

raw_data = (
    ('What a ridiculous concept!', 'Quel concept ridicule !'),
    ('Your idea is not entirely crazy.', "Votre idée n'est pas complètement folle."),
    ("A man's worth lies in what he is.", "La valeur d'un homme réside dans ce qu'il est."),
    ('What he did is very wrong.', "Ce qu'il a fait est très mal."),
    ("All three of you need to do that.", "Vous avez besoin de faire cela, tous les trois."),
    ("Are you giving me another chance?", "Me donnez-vous une autre chance ?"),
    ("Both Tom and Mary work as models.", "Tom et Mary travaillent tous les deux comme mannequins."),
    ("Can I have a few minutes, please?", "Puis-je avoir quelques minutes, je vous prie ?"),
    ("Could you close the door, please?", "Pourriez-vous fermer la porte, s'il vous plaît ?"),
    ("Did you plant pumpkins this year?", "Cette année, avez-vous planté des citrouilles ?"),
    ("Do you ever study in the library?", "Est-ce que vous étudiez à la bibliothèque des fois ?"),
    ("Don't be deceived by appearances.", "Ne vous laissez pas abuser par les apparences."),
    ("Excuse me. Can you speak English?", "Je vous prie de m'excuser ! Savez-vous parler anglais ?"),
    ("Few people know the true meaning.", "Peu de gens savent ce que cela veut réellement dire."),
    ("Germany produced many scientists.", "L'Allemagne a produit beaucoup de scientifiques."),
    ("Guess whose birthday it is today.", "Devine de qui c'est l'anniversaire, aujourd'hui !"),
    ("He acted like he owned the place.", "Il s'est comporté comme s'il possédait l'endroit."),
    ("Honesty will pay in the long run.", "L'honnêteté paye à la longue."),
    ("How do we know this isn't a trap?", "Comment savez-vous qu'il ne s'agit pas d'un piège ?"),
    ("I can't believe you're giving up.", "Je n'arrive pas à croire que vous abandonniez."),
)

def unicode_to_ascii(s):
    return ''.join(
        c for c in unicodedata.normalize('NFD', s)
        if unicodedata.category(c) != 'Mn')


def normalize_string(s):
    s = unicode_to_ascii(s)
    s = re.sub(r'([!.?])', r' \1', s)
    s = re.sub(r'[^a-zA-Z.!?]+', r' ', s)
    s = re.sub(r'\s+', r' ', s)
    return s

en_raw_data, de_raw_data = zip(*raw_data)
en_raw_data = [normalize_string(sentence) for sentence in en_raw_data]
de_raw_data_in = ["<start> " + normalize_string(sentence) for sentence in de_raw_data]
de_raw_data_out = [normalize_string(sentence) + " <end>" for sentence in de_raw_data]

en_tokenizer = Tokenizer(filters = "")
de_tokenizer = Tokenizer(filters = "")

en_tokenizer.fit_on_texts(en_raw_data)
de_tokenizer.fit_on_texts(de_raw_data_in)
de_tokenizer.fit_on_texts(de_raw_data_out)

en_data = en_tokenizer.texts_to_sequences(en_raw_data)
de_data_in = de_tokenizer.texts_to_sequences(de_raw_data_in)
de_data_out = de_tokenizer.texts_to_sequences(de_raw_data_out)

de_start_token = de_tokenizer.word_index["<start>"]
de_end_token = de_tokenizer.word_index["<end>"]

en_data = pad_sequences(en_data, padding = "post")
de_data_in = pad_sequences(de_data_in, padding = "post")
de_data_out = pad_sequences(de_data_out, padding = "post")
de_data_sequences_length = numpy.full((de_data_in.shape[0]), de_data_in.shape[1])

en_vocab_size = len(en_tokenizer.word_index) + 1
de_vocab_size = len(de_tokenizer.word_index) + 1

en_input_layer = Input(shape = [None], dtype = tensorflow.int32)
de_input_layer = Input(shape = [None], dtype = tensorflow.int32)
de_sequences_length_layer = Input(shape = [], dtype = tensorflow.int32)

EMBEDDING_SIZE = 32

en_embeddings = Embedding(en_vocab_size, EMBEDDING_SIZE)
de_embeddings = Embedding(de_vocab_size, EMBEDDING_SIZE)
en_input_embedding_layer = en_embeddings(en_input_layer)
de_input_embedding_layer = de_embeddings(de_input_layer)

LSTM_SIZE = 512

encoder = LSTM(LSTM_SIZE, return_state = True, return_sequences = True)
en_output, en_state_h, en_state_c = encoder(en_input_embedding_layer)
encoder_state = [en_state_h, en_state_c]

ATTENTION_UNITS = 1
attention_mechanism = LuongAttention(
    ATTENTION_UNITS, memory = encoder_state
)

decoder_cell = AttentionWrapper(
    LSTMCell(LSTM_SIZE), attention_mechanism, attention_layer_size = ATTENTION_UNITS
)

decoder = BasicDecoder(cell = decoder_cell, sampler = TrainingSampler(), output_layer = Dense(de_vocab_size))
BATCH_SIZE = 4
de_output, _, _ = decoder(de_input_embedding_layer, sequence_length = de_sequences_length_layer, initial_state = decoder_cell.get_initial_state(dtype = tensorflow.float32, batch_size = tensorflow.constant(BATCH_SIZE)))

logits = de_output.rnn_output
Y_proba = softmax(logits)
model = Model(
    inputs = [en_input_layer, de_input_layer, de_sequences_length_layer],
    outputs = [Y_proba]
)
model.compile(optimizer = "adam", loss = "sparse_categorical_crossentropy")

model.summary()

history = model.fit([en_data, de_data_in, de_data_sequences_length], de_data_out, epochs = 1000, batch_size = BATCH_SIZE)

model.save_weights("saved_model.h5")

en_data_test = tensorflow.constant(en_tokenizer.texts_to_sequences([normalize_string("I can't believe you're giving up.")]))
de_data_test = tensorflow.constant(de_tokenizer.texts_to_sequences(["<start> <start> <start> <start> <start> <start> <start> <start> <start> <start> <start> <start> <start> <start> <start>" + normalize_string("")]))
de_data_test_lengths = tensorflow.constant([15])

print(en_data_test.shape)
print(de_data_test.shape)
print(de_data_test_lengths.shape)
predictions = model.predict([en_data_test, de_data_test, de_data_test_lengths])
print(predictions.shape)
prediction = predictions[0]
word_indices = [numpy.argmax(proba) for proba in prediction]
words = [de_tokenizer.index_word[index] for index in word_indices if index != 0]
print(" ".join(words))

thank you so much.

**Comment by ageron** [comment]
Hi @thopv133802 ,

I'm finalizing a TFX tutorial for the TF World conference next week, so I'm afraid I don't have enough time right now to look at your code in detail. I'll be back in 2 weeks, and I'll try to help you then.

One small note: `tensorflow_core` is internal API. As is `keras.engine`, and so on. They could change in future versions, so you should use only the public API, like this:

```python
from tensorflow.keras.activations import softmax
from tensorflow.keras.layers import Input
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Embedding
from tensorflow.keras.layers import LSTM, LSTMCell
from tensorflow.keras import Model
```

In the meantime, I advise you to start with a demo example from TF Addons' website, ensure it runs well, then tweak it to your needs. Perhaps also ask your question on StackOverflow or TF Addons issues.

**Comment by thopv133802** [comment]
thank you.

**Comment by MichaelJanz** [comment]
Did you solved the issue? Because I have the exact same problem, when running the code as described in the chapter

**Comment by MichaelJanz** [comment]
@thopv133802 did you solved your issue?
I have the exact same problem, when running my code as written in the book. Disabling eager execution did not help me in that case
