### ISSUE TITLE
Chapter 2 Page 74 Transformation Pipelines

### ISSUE THREAD

**Issue by ismail-cheikh-boubaker** [ageron/handson-ml2#453]
the last line rises a TypeError : unhashable  type : 'numpy.ndarray ' 

from sklearn.compose import ColumnTransformer
num_attribs = list(housing_num)
cat_attribs = ["ocean_proximity"]
full_pipeline = ColumnTransformer([
("num", num_pipeline, num_attribs),
("cat", OneHotEncoder(), cat_attribs),
])
housing_prepared = full_pipeline.fit_transform(housing)

**Comment by Debassane** [comment]
Hi Ismail,
I have faced the same issue by conveiting the dtype into "int32" in 
the tranformer class function.
Here you go :

 rooms_per_household =rooms_per_household.astype ('int32')

Hope that's helping you

**Comment by ismail-cheikh-boubaker** [comment]
> Hi Ismail,
> I have faced the same issue . I have fixed it by converting the dtype into "int32" and starting the indexing by 2, instead of 3 in
> the tranformer class function.
> Here you go :
> 
> first code: rooms_ix, bedrooms_ix, population_ix, households_ix = 2, 3, 4, 5
> 
> second code: rooms_per_household =rooms_per_household.astype ('int32')
> 
> Hope that's helping you

Yes it worked, thank you so much.

**Comment by ageron** [comment]
Thanks for your question, @ismail-cheikh-boubaker , and thanks for the workaround @Debassane 👍 

However, I can't reproduce this issue. I've just run the [colab notebook](https://colab.research.google.com/github/ageron/handson-ml2/blob/master/02_end_to_end_machine_learning_project.ipynb), and it works fine:

![image](https://user-images.githubusercontent.com/76661/129525733-e14ed223-2a48-4d67-b046-831f19f13a5f.png)

Could you please tell me which version of Python, Scikit-Learn, NumPy and Pandas you are running? Are you running the code locally or on Colab? If possible, could you please give me a minimal code example which reproduces the issue? Thanks a lot!
