### ISSUE TITLE
[QUESTION] Use of clone_model() 

### ISSUE THREAD

**Issue by juliotorrest** [ageron/handson-ml2#454]
Hello!
I am going through Chapter 11,  "Reusing Pretrained Layers" section.

On cell 60, model_B_on_A is created from a pretrained model:

`model_B_on_A = keras.models.Sequential(model_A.layers[:-1])`

Then, on cell 61, the original model is cloned:

```
model_A_clone = keras.models.clone_model(model_A)
model_A_clone.set_weights(model_A.get_weights())
```

Finally, on cell 62 the model is compiled. 
My question is, shouldn't model_B_on_A use 'model_A_clone' instead of 'model_A'? I guess it makes no difference, but it is just not 100% clear to me.
Thanks in advance!

**Comment by ageron** [comment]
I added a comment in the notebook to clarify this, and I decided to just create `model_B_on_A` a second time, so it uses the cloned model. Thanks again @juliotorrest !
