### ISSUE TITLE
[QUESTION][Chapter 11] `lr` argument is deprecated in Keras 2.3.0 for all optimizers

### ISSUE THREAD

**Issue by hms5232** [ageron/handson-ml2#456]
I'm not sure which type this issue should belong to. If the issue type is wrong, just tell me and i will edit it.

I recently ran [chapter 11 code on Colab](https://colab.research.google.com/github/ageron/handson-ml2/blob/master/11_training_deep_neural_networks.ipynb), noticed python return some warning about `keras.optimizers`:
```
$ optimizer = keras.optimizers.SGD(lr=0.001, momentum=0.9)
/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/optimizer_v2/optimizer_v2.py:375: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  "The `lr` argument is deprecated, use `learning_rate` instead.")
```
Almost all optimizers that use the `lr` parameter have this warning
```
$ optimizer = keras.optimizers.Adagrad(lr=0.001)
/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/optimizer_v2/optimizer_v2.py:375: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  "The `lr` argument is deprecated, use `learning_rate` instead.")
```

The warning message:
```
/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/optimizer_v2/optimizer_v2.py:375: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  "The `lr` argument is deprecated, use `learning_rate` instead.")
```

After changing param, this warning disappear and code work perfectly. Maybe we should update code to new argument name?
```
optimizer = keras.optimizers.SGD(learning_rate=0.001, momentum=0.9)  # replace "lr" with "learning_rate"
```

here are reference from keras github release page:
https://github.com/keras-team/keras/releases/tag/2.3.0

English is not my native language; please excuse typing errors. Thank you :)

**Comment by ageron** [comment]
Thanks @hms5232 ! 👍 

Indeed `learning_rate` should now be used instead of `lr`. Note that the Jupyter notebooks still run without a problem, despite the warnings, since `lr` has not been removed yet. But of course I'll update the notebooks asap.
