### ISSUE TITLE
Theory Questions K Means for Preprocessing 

### ISSUE THREAD

**Issue by VirajVaitha123** [ageron/handson-ml2#47]
Hi There,

I hope you're well.

Thank you for your book, it's been really useful and enjoyed reading it.

I was wondering if you could helped clarify this issue for me:
When we use Kmeans for preprocessing, where is the distance computed, and stored where?

For example,
You place KMeans and Logistic Regression into a Pipeline and use the .fit() method. 

I understand that we are trying to get the distances of each value from it's cluster, but does KMeans.fit(xtrain,ytrain) actually do this? Or is it initiated when we run the gridsearchCV. If this is the case, what is the sequence of steps and how do we know what's being performed.

I know I didn't phrase this well but happy to try rephrase it again?

Thanks,

Viraj

**Comment by VirajVaitha123** [comment]
Sorry I figured this out now.

For anyone interested,
Pipeline will run transforms on subsequent steps and .fit on the final one.
In our case it ran fit_transform for KMeans. (It fit to the data to create it's clusters, and then transformed the data from pixel intensities to the distance from it's clusters.

The distance from each cluster centre is used as features in the logistic regressor. We have also now reduce the dimensionality of the dataset from number of pixels making up the image (64) to 50 (the number of clusters)

Thanks

**Comment by ageron** [comment]
Hi @VirajVaitha123 ,
You got it exactly right, thanks for adding this great answer to your own question.
Cheers!
