### ISSUE TITLE
Which hyper parameter should I fine-tune first

### ISSUE THREAD

**Issue by Kirushikesh** [ageron/handson-ml2#477]
Hi to the reader,

In chapter 2 of **Hands-on machine learning with scikit-learn, keras & Tensorflow**. The author explained how to do fine-tuning and how fine-tuning improves the result. As an illustration, the author used grid-search CV to fine-tune **max_features** and **n_estimators** hyperparameters in the Random Forest Regressor.

My question is out of various hyper-parameters available in scikit-learn implementation of Random Forest Regressor. How do I choose the optimal hyperparameters to tune first? I know one of the answers is to tune all the available ones. But if time was my constraint here. How do I give importance to various hyperparameters available? 

`
class sklearn.ensemble.RandomForestRegressor(n_estimators=100, *, criterion='squared_error', max_depth=None, min_samples_split=2, min_samples_leaf=1, min_weight_fraction_leaf=0.0, max_features='auto', max_leaf_nodes=None, min_impurity_decrease=0.0, bootstrap=True, oob_score=False, n_jobs=None, random_state=None, verbose=0, warm_start=False, ccp_alpha=0.0, max_samples=None)
`

These are the various hyperparameters available in scikit-learn Random Forest `Regressor, I am a newbie in ML ocean so apology if this is a silly question or my question itself wrong.

**Comment by ageron** [comment]
Hi @Kirushikesh ,
Thanks for your question. The most important hyperparameters to tune in a Random Forest are `n_estimators` and `max_features` (see [Scikit-Learn's user guide](https://scikit-learn.org/stable/modules/ensemble.html#parameters) for more details).

Hope this helps.
