### ISSUE TITLE
Chap 2: Why we don't use .copy() for training set, but use it for training lable?

### ISSUE THREAD

**Issue by ladylazy9x** [ageron/handson-ml2#481]
> housing = strat_train_set.drop("median_house_value", axis=1) # drop labels for training set
> housing_labels = strat_train_set["median_house_value"].copy()

In the gaining insight we use this `housing = strat_train_set.copy()` so we can play with housing without affect original data. So why we don't use .copy() for training set, but use it for training lable? Any difference? Could you clarify?

**Comment by ageron** [comment]
Hi @ladylazy9x ,
Thanks for your questions.
The `drop()` method returns a copy of the DataFrame with one column removed. So there's no need to call `copy()`, since it's already a copy.
Hope this helps.
