### ISSUE TITLE
[QUESTION] 02_end_to_end_machine_learning_project.ipynb cell #66-69

### ISSUE THREAD

**Issue by raindata5** [ageron/handson-ml2#484]
Good Afternoon! I'm loving the book so far it's a bit difficult for me but very informative 😁👍. I just had a little question in chapter 2.

**Describe what is unclear to you**
For cell #66-69 in this particular portion of the project we used a OneHotEncoder which was the natural decision when dealing with a regression and categorical values. However I notice when running this encoder it doesn't exclude one of the variables as a reference category.
So for example there are 5 unique values in the ocean_proximity column and if you run 

**_cat_encoder.categories__**

this returns all the 5 categories.
Also to confirm if you run 

**_cat_encoder = OneHotEncoder()
cat_variables = cat_encoder.fit_transform(X)
cat_variables.toarray().shape_**

on the array that's returned then it shows 5 columns.
So I'm just curious to know if this is the intended effect?

**Versions (please complete the following information):**
scikit-learn==1.0
Python 3.8.10

**Additional context**
Now looking at the documention as well for the OneHotEncoder it shows one can specify an argument for the drop parameter.
However it says that's for the fear that the variables one is transforming are collinear but nothing about a reference category/base level is mentioned there.

**Comment by ageron** [comment]
Hi @raindata5 ,

Thanks for your kind words and your interesting question.

Indeed, the `OneHotEncoder` does not drop a category by default. As you point out it's possible to use the `drop` hyperparameter if you *do* want to drop a category. For example, `drop="first"` will drop the first category in each feature, `drop="is_binary"` will drop the first category as well, but only for binary features, and `drop=["Foo", "Bar", ...]` will drop category `"Foo"` for the 1st feature, `"Bar"` for the 2nd feature, and so on.

As the documentation for the `drop` hyperparameter points out, if you choose to drop a category, then it breaks the symmetry between the categories, and the model may treat the reference category differently from the others. Perhaps that's okay, but it depends on the use case.

Also, if you expect to get occasional unknown categories in production, then you will want to set `handle_unknown="ignore"`. Then, when an unknown category appears, it will be treated exactly as if it were the reference category. Again, perhaps that's exactly what you want, or perhaps not: it really depends on the use case.

In practice, I've always used `OneHotEncoder` without setting the `drop` hyperparameter. Next time I use it, I'll try dropping a category to see if it makes a difference. 👍 

Here's a little demo to show that unknown categories are treated exactly like the reference category, when you define one:

```python
>>> encoder = OneHotEncoder(drop=["Foo", "Bar"], handle_unknown="ignore", sparse=False)
>>> encoder.fit_transform([
...      ["Foo", "B1"],
...      ["A1", "Bar"],
...      ["A2", "B1"]])
...
array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 1.]])
>>> encoder.transform([["Foo", "Bar"]])
array([[0., 0., 0.]])
>>> encoder.transform([["New", "Other"]])
```

Lastly, although the colinear issue can theoretically happen, in practice I've never run into it. You would have to be using unregularized linear regression, and have at least as many categories as samples, which almost never happens.

Hope this helps! 😊

**Comment by raindata5** [comment]
Wow thanks a lot for the detailed response! It was more than I was expecting lol. Thanks a lot for the help! I will keep it all in mind as I'm sure it'll prove beneficial. Especially the idea of passing a list into drop since I recently used the **OneHotEncoder** on two categorical features. So definitely all helpful thanks again! 😁👍
