### ISSUE TITLE
[QUESTION] Chapter 4: plot_learning_curves function

### ISSUE THREAD

**Issue by alexdombos** [ageron/handson-ml2#487]
**Describe what is unclear to you**
In Chapter 4, the ```plot_learning_curves(model, X, y)``` function plots a model's performance as a function of the training set size (or training iteration). This function is defined on pages 133-134 of the book and cell 35 of the Jupyter notebook 04_training_linear_models.ipynb.

```plot_learning_curves``` has a for loop that begins as follows:
```python
for m in range(1, len(X_train)):
    model.fit(X_train[:m], y_train[:m])
```

Is there a particular reason the last instance of the training set is not used? Based on the way it is written, I would think that the entire training set is intended to be used in the last iteration of the for loop. If that is the case, the for loop should be:
```python
for m in range(1, len(X_train) + 1):
    model.fit(X_train[:m], y_train[:m])
```

This seems like a very minor off-by-one error.

**To Reproduce**

This minimal working example shows the problem:
```python
#!/usr/bin/env python3

import numpy as np

X_train = np.array([0, 1, 2, 3])

for m in range(1, len(X_train)):
    print(X_train[:m])
print('=====')
for m in range(1, len(X_train) + 1):
    print(X_train[:m])
```
Output:
```
[0]
[0 1]
[0 1 2]
=====
[0]
[0 1]
[0 1 2]
[0 1 2 3]
```

**Comment by ageron** [comment]
Ah indeed, thanks for you feedback, I'll fix this now. 👍
