### ISSUE TITLE
02_end_to_end_machine_learning_project DOWNLOAD_ROOT

### ISSUE THREAD

**Issue by jmcuadra2** [ageron/handson-ml2#49]
Hi,
In notebook 02_end_to_end_machine_learning_project DOWNLOAD_ROOT should be changed to https://github.com/ageron/handson-ml2/tree/master/
Thanks.

**Comment by ageron** [comment]
Hi @jmcuadra2 ,
Thanks for your suggestion. However, the correct URL to download the data is the one currently used in the notebook:

```python
DOWNLOAD_ROOT = "https://raw.githubusercontent.com/ageron/handson-ml2/master/"
```

This allows the code to download the data file itself, and it works fine (did you run into any error?).

If we used `https://github.com/ageron/handson-ml2/tree/master/` instead, the code would download the HTML page that describes the file. Indeed, try visiting this URL:
https://github.com/ageron/handson-ml2/tree/master/datasets/housing/housing.tgz

You will notice that no download takes place, you just reach a page that describes the file. If you use the following URL instead, you will see that the file will be downloaded:

https://raw.githubusercontent.com/ageron/handson-ml2/master/datasets/housing/housing.tgz

I hope this helps.
