### ISSUE TITLE
[BUG] Chapter 7 Exercise # 8 - Voting Classifier estimators scores doesn't work

### ISSUE THREAD

**Issue by d1amondb0t** [ageron/handson-ml2#492]
Hi,
This doesn't effect the flow of the exercise, but when I was correcting my work and saw this, I realized that it wasn't outputting the scores of the estimators in the votingClassifier when running threw it. I tested this on the jupyter notebook and google colab.

**To Reproduce**
Please copy the code that fails here, using code blocks like this:

```python
[estimator.score(X_val, y_val) for estimator in voting_clf.estimators_]

```

And if you got an exception, please copy the full stacktrace here:

**Expected behavior**
Well, we should be getting the values of the score of each estimator.

**Screenshots**
![Screenshot 2021-10-29 164012](https://user-images.githubusercontent.com/81024527/139499120-636752e9-9498-473a-a94c-4beddcbd21fa.png)

**Versions (please complete the following information):**
 - OS: Windows
 - Python: 3.9
 - TensorFlow: [e.g., 2.4.1]
 - Scikit-Learn: [e.g., 0.24.1]
- Other libraries that may be connected with the issue: [e.g., gym 0.18.0]

**Comment by ageron** [comment]
Hi @d1amondb0t ,

Thanks for your feedback. I tried to reproduce this error, but everything worked fine for me. Could you please run the following code and verify that it produces something similar to the output below? If not, then please copy/paste the output in a comment below.

```python
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.datasets import make_moons
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import VotingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC

sklearn.show_versions()
X, y = make_moons(n_samples=500, noise=0.30, random_state=42)
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

log_clf = LogisticRegression(solver="lbfgs", random_state=42)
rnd_clf = RandomForestClassifier(n_estimators=100, random_state=42)
svm_clf = SVC(gamma="scale", probability=True, random_state=42)
voting_clf = VotingClassifier(
    estimators=[('lr', log_clf), ('rf', rnd_clf), ('svc', svm_clf)],
    voting='soft')
voting_clf.fit(X_train, y_train)

print("Voting classifier:", voting_clf.score(X_test, y_test))

for index, estimator in enumerate(voting_clf.estimators_):
    print(f"Estimator {index}: {estimator.score(X_test, y_test)}")
```

The output should look like this (the versions at the start may differ a bit):

```
System:
    python: 3.8.12 | packaged by conda-forge | (default, Oct 12 2021, 21:50:38)  [Clang 11.1.0 ]
executable: /Users/ageron/miniconda3/envs/test/bin/python
   machine: macOS-10.15.7-x86_64-i386-64bit

Python dependencies:
          pip: 21.3
   setuptools: 58.2.0
      sklearn: 1.0.1
        numpy: 1.19.5
        scipy: 1.7.1
       Cython: None
       pandas: 1.3.3
   matplotlib: 3.4.3
       joblib: 0.14.1
threadpoolctl: 3.0.0

Built with OpenMP: True
Voting classifier: 0.92
Estimator 0: 0.864
Estimator 1: 0.896
Estimator 2: 0.896
```

**Comment by d1amondb0t** [comment]
Hi,
I tried uninstalling and reinstalling the libraries and it ended up working just fine. I don't know why that is, but thanks none the less.
