### ISSUE TITLE
[BUG] 'module' object is not callable - StandardScaler - Chapter 4 Early stopping

### ISSUE THREAD

**Issue by ladylazy9x** [ageron/handson-ml2#497]
When run the whole code the code block work fine but I only want to run part of the code and import necessary package. 

```python
from sklearn.preprocessing import PolynomialFeatures
from copy import deepcopy
from sklearn.metrics import mean_squared_error
import sklearn.pipeline as Pipeline
from sklearn.preprocessing import StandardScaler


poly_scaler = Pipeline([
        ("poly_features", PolynomialFeatures(degree=90, include_bias=False)),
        ("std_scaler", StandardScaler())
    ])

X_train_poly_scaled = poly_scaler.fit_transform(X_train)
X_val_poly_scaled = poly_scaler.transform(X_val)

sgd_reg = SGDRegressor(max_iter=1, tol=-np.infty, warm_start=True,
                       penalty=None, learning_rate="constant", eta0=0.0005, random_state=42)

minimum_val_error = float("inf")
best_epoch = None
best_model = None
for epoch in range(1000):
    sgd_reg.fit(X_train_poly_scaled, y_train)  # continues where it left off
    y_val_predict = sgd_reg.predict(X_val_poly_scaled)
    val_error = mean_squared_error(y_val, y_val_predict)
    if val_error < minimum_val_error:
        minimum_val_error = val_error
        best_epoch = epoch
        best_model = deepcopy(sgd_reg)
```

It point to  `("std_scaler", StandardScaler())` said `'module' object is not callable `where as previous code in Polynomial Regression work fine. Do you know how to fix?

**Comment by ageron** [comment]
Hi @ladylazy9x ,

When I run this code, the error points to the line `poly_scaler = Pipeline([`, and indeed, `Pipeline` is a module instead of a class. If you look at the import, you'll see that you wrote:

```python
import sklearn.pipeline as Pipeline  # <= wrong
```

instead of:

```python
from sklearn.pipeline import Pipeline  # <= right
```

You also need to add:

```python
from sklearn.linear_model import SGDRegressor

X_train = ...
y_train = ...
X_val = ...
y_val = ...
```

Hope this helps.

**Comment by ageron** [comment]
p.s. you can get Python syntax highlighting in github by writing:

\`\`\`python
from sklearn.preprocessing import PolynomialFeatures
...
\`\`\`

This is the result:

```python
from sklearn.preprocessing import PolynomialFeatures
...
```

It works with many other languages too. 👍

**Comment by ageron** [comment]
And you can also put long stacktraces and other details in a \<details\> section like this:

```
<details>
Long details:

* blabla
* blabla
* bla
</details>
```

This is the result:

<details>
Long details:

* blabla
* blabla
* bla
</details>

**Comment by ladylazy9x** [comment]
> Hi @ladylazy9x ,
> 
> When I run this code, the error points to the line `poly_scaler = Pipeline([`, and indeed, `Pipeline` is a module instead of a class. If you look at the import, you'll see that you wrote:
> 
> ```python
> import sklearn.pipeline as Pipeline  # <= wrong
> ```
> 
> instead of:
> 
> ```python
> from sklearn.pipeline import Pipeline  # <= right
> ```
> 
> You also need to add:
> 
> ```python
> from sklearn.linear_model import SGDRegressor
> 
> X_train = ...
> y_train = ...
> X_val = ...
> y_val = ...
> ```
> 
> Hope this helps.

Great! thanks, and I will remember to put ` ```python`
