### ISSUE TITLE
[QUESTION] Chapter 2. Why must the feature importances be calculated for each combination?

### ISSUE THREAD

**Issue by heerboi** [ageron/handson-ml2#498]
In the CH2 ipynb, after cell 125, the following has been said: 

**"Note: this feature selector assumes that you have already computed the feature importances somehow (for example using a RandomForestRegressor). You may be tempted to compute them directly in the TopFeatureSelector's fit() method, however this would likely slow down grid/randomized search since the feature importances would have to be computed for every hyperparameter combination (unless you implement some sort of cache)."**

My question is that, why do these feature importances have to be calculated each time, since the data preparation before passing them to GridSearch/RandomizedSearch would happen only once? And also, why will they be different for each combination?

Thank you.

**Comment by ageron** [comment]
Hi @heerboi ,

Thanks for your question.

There are two scenarios:

1. Prepare all the data, then use `GridSearchCV` on the predictor only.
2. Use `GridSearchCV` on the full pipeline, including the preparation steps + the predictor.

In the first case, you're right, the feature importances would only be calculated once, no problem.

In the second case, the whole pipeline would run for every hyperparameter combination. In some cases that's exactly what you want, for example if you want to tune hyperparameters of the preparation itself. In fact, the important features may vary depending on the preparation hyperparameters, so in some cases it may be a good thing to leave the selection as part of the pipeline, in the `fit()` method. To speed things up, Scikit-Learn added a caching mechanism in version 0.19: if you set the `Pipeline`'s `memory` hyperparameter to the path to a cache directory, it will store the pipeline's fitted estimators for each combination of hyperparameters, which may speed things up a lot.

I hope this helps.
