### ISSUE TITLE
[Book 2nd Edition] Error 404 for link in book 

### ISSUE THREAD

**Issue by aishwaryaprabhat** [ageron/handson-ml2#5]
Hi @ageron I was going through the second edition of the book which was available for free. On page xii in the Preface, under "Machine Learning in Your Projects", the hyperlink https://www.kaggle.com/wiki/DataScienceUseCases at "And more" is not available on the kaggle website anymore. 

P.S. I am the Data Scientist from Shopee who was very excited to meet you at the Singapore AI Meetup :)

**Comment by ageron** [comment]
Oh no, they deleted the page! It should be forbidden to delete anything on the web. ;-)
Thanks a lot for your feedback, I've updated the book with a new URL that I can control in the future: https://homl.info/usecases
Thanks again!
