### ISSUE TITLE
How the target attribute be represented for a multi-class classification problem?

### ISSUE THREAD

**Issue by Kirushikesh** [ageron/handson-ml2#500]
An amateurish question, I have a multi-class classification problem with output categories [ 'A' , 'B' , 'C' ]. So should i need to convert the y=[ "A", "A", "B" , "C" ] into [0,0,1,2] (or) into [[1,0,0],[1,0,0],[0,1,0],[0,0,1]], in which way should i need to convert my target attribute. In Chapter 3 the @ageron  used the first method. But in scikit-learn .fit(X,y) method states **y: array-like of shape (n_samples,) or (n_samples, n_outputs)** .

(n_samples, n_outputs) implies the 2nd method right? @ageron please help me

**Comment by ageron** [comment]
Hi @Kirushikesh ,

Welcome to Machine Learning! 👍 

Scikit-Learn classifiers generally expect a 1D array as the target. It can contain numbers or strings, both work fine. For example, let's try both on a `LogisticRegression` predictor:

```python
import numpy as np
from sklearn.linear_model import LogisticRegression

X = np.random.rand(10, 3)
y = np.array([1, 1, 0, 3, 1, 2, 1, 2, 0, 1])

lin_reg = LogisticRegression()
lin_reg.fit(X, y)

print(lin_reg.classes_)  #> [0 1 2 3]
print(lin_reg.predict(X))  #> something like [1 0 2 0 0 1 0 0 1 3]

y = np.array(["B", "B", "A", "D", "B", "C", "B", "C", "A", "B"])
lin_reg.fit(X, y)
print(lin_reg.classes_)  #> ['A' 'B' 'C' 'D']
print(lin_reg.predict(X))  #> something like ['B' 'A' 'C' 'A' 'A' 'B' 'A' 'A' 'B' 'D']
```

However, if we try to one-hot encode the targets, it doesn't work with `LogisticRegression`:

```python
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(sparse=False)
y_onehot = encoder.fit_transform(y.reshape(-1, 1))
lin_reg.fit(X, y_onehot)  #!!! ValueError: y should be a 1d array
```

However, it *does* work for a `RandomForestClassifier` because it supports having multiple outputs:

```python
from sklearn.ensemble import RandomForestClassifier

rnd_clf = RandomForestClassifier()
rnd_clf.fit(X, y_onehot)
print(rnd_clf.predict(X))  #> [[0. 1. 0. 0.] [0. 1. 0. 0.] ...]
```

Hope this helps.

**Comment by Kirushikesh** [comment]
Gotcha. So to conclude not all classifiers in scikit-learn supports one-hot encoded target attributes. Its better to keep our target as 1D vector, both work similarly we can use any method. Thanks @ageron !!!
