### ISSUE TITLE
[QUESTION] Simplification of Equation 7.1?

### ISSUE THREAD

**Issue by claudio525** [ageron/handson-ml2#507]
In Chapter 7 on AdaBoost, the equation (7.1) for the weighted error rate of the j-th predictor is from my understanding, the sum of the weights of the incorrectly classified samples divided by the sum of all weights. However, since these weights are normalized (as per equation 7.3), there isn't any reason to divide by the sum of all weights as that will always be 1. Is this correct or am missing something?

**Comment by ageron** [comment]
Hi @claudio525 ,

Thanks for your feedback. You're right, equation 7.1 can be simplified by removing the denominator, since it's always equal to 1 due to the normalization step.

I'll update the book. Thanks again! 👍
