### ISSUE TITLE
Chapter 3 | KeyError 

### ISSUE THREAD

**Issue by OmarioHassan** [ageron/handson-ml2#518]
**Describe the bug**
I'm new in this track and was applying the same code as chapter 3 classification
I first loaded MNIST dataset correctly then tried to show the first-row image but got an error

<img width="500" alt="image" src="https://user-images.githubusercontent.com/8146344/147400055-22df340b-4e7e-4df6-9193-14fd420ebeab.png">

After search I found that `reshape` is working with numpy so I fixed it like this

![image](https://user-images.githubusercontent.com/8146344/147400076-48dd1bb3-2a90-4288-9f9d-dbe2167bad6c.png)

And I'm not sure is this solution looks correct or not 

thanks in advance

```stacktrace
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~/.conda/envs/default/lib/python3.9/site-packages/pandas/core/indexes/base.py in get_loc(self, key, method, tolerance)
   3360             try:
-> 3361                 return self._engine.get_loc(casted_key)
   3362             except KeyError as err:

~/.conda/envs/default/lib/python3.9/site-packages/pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

~/.conda/envs/default/lib/python3.9/site-packages/pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 0

The above exception was the direct cause of the following exception:

KeyError                                  Traceback (most recent call last)
/tmp/ipykernel_125/2984276903.py in <module>
      2 import matplotlib.pyplot as plt
      3 
----> 4 some_digit = X[0]
      5 some_digit_image = some_digit.reshape(28,28)
      6 

~/.conda/envs/default/lib/python3.9/site-packages/pandas/core/frame.py in __getitem__(self, key)
   3456             if self.columns.nlevels > 1:
   3457                 return self._getitem_multilevel(key)
-> 3458             indexer = self.columns.get_loc(key)
   3459             if is_integer(indexer):
   3460                 indexer = [indexer]

~/.conda/envs/default/lib/python3.9/site-packages/pandas/core/indexes/base.py in get_loc(self, key, method, tolerance)
   3361                 return self._engine.get_loc(casted_key)
   3362             except KeyError as err:
-> 3363                 raise KeyError(key) from err
   3364 
   3365         if is_scalar(key) and isna(key) and not self.hasnans:

KeyError: 0
```

**Comment by OmarioHassan** [comment]
The same error will happen in the prediction part

<img width="642" alt="image" src="https://user-images.githubusercontent.com/8146344/147400454-e0638e2a-cd24-4f87-9678-3ed73165538f.png">

So I fixed it like this 

<img width="297" alt="image" src="https://user-images.githubusercontent.com/8146344/147400460-b0c4a52c-2a27-4af9-83f6-22f8bcc857ce.png">

**Comment by ageron** [comment]
Hi,
I can't write a long response right now, but the solution is to add as_frame=False when calling fetch_openml(). This function used to return a NumPy array by default, but it changed to returning a Pandas Dataframe by default, which breaks stuff. By setting as_frame=False, you force it to return a NumPy array, as before.
Hope this helps.

**Comment by markfilan** [comment]
This annoying error means that Pandas can not find your column name in your dataframe.  Before doing anything with the data frame, use print(df.columns) to see [dataframe column exist or not](http://net-informations.com/ds/pd/exists.htm).

`print(df.columns)`

I was getting a similar kind of error in one of my codes. Turns out, that particular index was missing from my data frame as I had dropped the empty dataframe 2 rows. If this is the case, you can do df.reset_index(inplace=True) and the error should be resolved.
