### ISSUE TITLE
environment.yml should be in docker

### ISSUE THREAD

**Issue by JulianSMoore** [ageron/handson-ml2#52]
This is hard work for someone who a) doesn't do linux, b) just installed docker in complete ignorance in linux under vmware because win10 home... z)

I think there's a problem: error in docker build

Step 4/20 : COPY docker/environment.yml /tmp/
ERROR: Service 'handson-ml2' failed to build: COPY failed: stat /var/lib/docker/tmp/docker-builder812836084/docker/environment.yml: no such file or directory
Makefile:9: recipe for target 'build' failed

because dockerfile contains

RUN conda update -n base conda
COPY docker/environment.yml /tmp/
RUN conda env create -f /tmp/environment.yml

but environment.yml is not in docker/

(After copying it in I got to step 5 of 20 and "enabling notebook extension"... validating... done
and then a valid environment seems to be built

Now I can get to step 15, but there's a new error...

Service 'handson-ml2' failed to build: The command '/bin/sh -c git-nbdiffdriver config --enable --global' returned a non-zero code: 127...

ah, probably because

/bin/sh: 1: git-nbdiffdriver: not found

on the line above

**Comment by ageron** [comment]
Thanks for your feedback @JulianSMoore. I think what happened is that I had a lot of stuff in `environment.yml`, a bit too much, and it caused some errors for some people as some packages were not found. So I did a big cleanup in that file, and unfortunately I seem to have removed some important package. Sorry about that. As you can tell, I have room for improvement on docker packaging, I'm sorry about that. I'll try to fix this today. Thanks for your understanding.

**Comment by ageron** [comment]
I fixed the Dockerfile: if you git pull then run make build in the docker directory, it should work now, sorry for the inconvenience.
