### ISSUE TITLE
Cannot access container & it only runs (exit code 0) for seconds

### ISSUE THREAD

**Issue by JulianSMoore** [ageron/handson-ml2#53]
After copying environment.yml to the right place and commenting out git.nbdiff (why didn't it work?) the container built successfully but a) starting it from Portainer it runs for a few seconds and then seems to stop and b) even if I was fast I could not access anything on localhost:8888

I might have the port wrong, but can't recall where it it was set or work out anything else to do with the container.

I am only interested in the python and ML and have no experience of LINUX or Docker, and I suspect I and others like me would benefit from more explicit explanations of how to run this - it looks fantastic in prospect!

Would appreciate your expert advice :)

The last build output was:

> olop@Minty ~/Downloads/handson-ml2-master/docker $ docker-compose build
> Building handson-ml2
> Step 1/19 : FROM continuumio/miniconda3:latest
>  ---> 406f2b43ea59
> Step 2/19 : RUN apt-get update && apt-get upgrade -y     && apt-get install -y         libpq-dev         build-essential         git         sudo         cmake zlib1g-dev libjpeg-dev xvfb ffmpeg xorg-dev libboost-all-dev libsdl2-dev swig         unzip zip     && rm -rf /var/lib/apt/lists/*
>  ---> Using cache
>  ---> 09dbaee5152a
> Step 3/19 : RUN conda update -n base conda
>  ---> Using cache
>  ---> c8ad38ddfa7e
> Step 4/19 : COPY docker/environment.yml /tmp/
>  ---> Using cache
>  ---> 6d80800eddca
> Step 5/19 : RUN conda env create -f /tmp/environment.yml
>  ---> Using cache
>  ---> f5108c8f9e87
> Step 6/19 : ARG username
>  ---> Using cache
>  ---> c37e2d9a8754
> Step 7/19 : ARG userid
>  ---> Using cache
>  ---> 30bd5ca16a55
> Step 8/19 : ARG home=/home/${username}
>  ---> Using cache
>  ---> e8d4e94deb07
> Step 9/19 : ARG workdir=${home}/handson-ml2
>  ---> Using cache
>  ---> 337be092376a
> Step 10/19 : RUN adduser ${username} --uid ${userid} --gecos '' --disabled-password     && echo "${username} ALL=(root) NOPASSWD:ALL" > /etc/sudoers.d/${username}     && chmod 0440 /etc/sudoers.d/${username}
>  ---> Using cache
>  ---> 2c0fbd3c6e5b
> Step 11/19 : WORKDIR ${workdir}
>  ---> Using cache
>  ---> 77728e3a0ce7
> Step 12/19 : RUN chown ${username}:${username} ${workdir}
>  ---> Using cache
>  ---> 71dae86963b8
> Step 13/19 : USER ${username}
>  ---> Using cache
>  ---> bfb3057bacbe
> Step 14/19 : WORKDIR ${workdir}
>  ---> Using cache
>  ---> 74a1a41cdc47
> Step 15/19 : COPY docker/bashrc.bash /tmp/
>  ---> 9287d9083afe
> Step 16/19 : RUN cat /tmp/bashrc.bash >> ${home}/.bashrc
>  ---> Running in 74fb5bed35ce
> Removing intermediate container 74fb5bed35ce
>  ---> 4474776e18d3
> Step 17/19 : RUN echo "export PATH=\"${workdir}/docker/bin:$PATH\"" >> ${home}/.bashrc
>  ---> Running in 5e97fbd7e8b9
> Removing intermediate container 5e97fbd7e8b9
>  ---> b265c7b1aeee
> Step 18/19 : RUN sudo rm /tmp/bashrc.bash
>  ---> Running in 5a858f4d5a33
> Removing intermediate container 5a858f4d5a33
>  ---> a23ae6dd4a93
> Step 19/19 : RUN mkdir -p ${home}/.jupyter &&     echo 'c.NotebookApp.password = u"sha1:c6bbcba2d04b:f969e403db876dcfbe26f47affe41909bd53392e"'     >> ${home}/.jupyter/jupyter_notebook_config.py
>  ---> Running in f13c82dc15cd
> Removing intermediate container f13c82dc15cd
>  ---> 0f02601cf182
> Successfully built 0f02601cf182
> Successfully tagged handson-ml2:latest
> 

the edited Dockerfile is like this

```
FROM continuumio/miniconda3:latest

RUN apt-get update && apt-get upgrade -y \
    && apt-get install -y \
        libpq-dev \
        build-essential \
        git \
        sudo \
        cmake zlib1g-dev libjpeg-dev xvfb ffmpeg xorg-dev libboost-all-dev libsdl2-dev swig \
        unzip zip \
    && rm -rf /var/lib/apt/lists/*

RUN conda update -n base conda
COPY docker/environment.yml /tmp/
RUN conda env create -f /tmp/environment.yml

ARG username
ARG userid

ARG home=/home/${username}
ARG workdir=${home}/handson-ml2

RUN adduser ${username} --uid ${userid} --gecos '' --disabled-password \
    && echo "${username} ALL=(root) NOPASSWD:ALL" > /etc/sudoers.d/${username} \
    && chmod 0440 /etc/sudoers.d/${username}

WORKDIR ${workdir}
RUN chown ${username}:${username} ${workdir}

USER ${username}
WORKDIR ${workdir}

# The config below enables diffing notebooks with nbdiff (and nbdiff support
# in git diff command) after connecting to the container by "make exec" (or
# "docker-compose exec handson-ml2 bash")
#       You may also try running:
#         nbdiff NOTEBOOK_NAME.ipynb
#       to get nbdiff between checkpointed version and current version of the
# given notebook.

# commented out 1/11/2019 22:31
# RUN git-nbdiffdriver config --enable --global

# INFO: Optionally uncomment any (one) of the following RUN commands below to ignore either
#       metadata or details in nbdiff within git diff
#RUN git config --global diff.jupyternotebook.command 'git-nbdiffdriver diff --ignore-metadata'
# commented out 1/11/2019 22:31
# RUN git config --global diff.jupyternotebook.command 'git-nbdiffdriver diff --ignore-details'


COPY docker/bashrc.bash /tmp/
RUN cat /tmp/bashrc.bash >> ${home}/.bashrc
RUN echo "export PATH=\"${workdir}/docker/bin:$PATH\"" >> ${home}/.bashrc
RUN sudo rm /tmp/bashrc.bash


# INFO: Uncomment lines below to enable automatic save of python-only and html-only
#       exports alongside the notebook
# COPY docker/jupyter_notebook_config.py /tmp/
# RUN cat /tmp/jupyter_notebook_config.py >> ${home}/.jupyter/jupyter_notebook_config.py
# RUN sudo rm /tmp/jupyter_notebook_config.py


# INFO: Uncomment the RUN command below to disable git diff paging
# RUN git config --global core.pager ''


# INFO: Uncomment the RUN command below for easy and constant notebook URL (just localhost:8888)
#       That will switch Jupyter to using empty password instead of a token.
#       To avoid making a security hole you SHOULD in fact not only uncomment but
#       regenerate the hash for your own non-empty password and replace the hash below.
#       You can compute a password hash in any notebook, just run the code:
#          from notebook.auth import passwd
#          passwd()
#       and take the hash from the output

# uncommented 1/11/2019 22:22:33
RUN mkdir -p ${home}/.jupyter && \
    echo 'c.NotebookApp.password = u"sha1:c6bbcba2d04b:f969e403db876dcfbe26f47affe41909bd53392e"' \
    >> ${home}/.jupyter/jupyter_notebook_config.py
```

**Comment by ageron** [comment]
I fixed the Dockerfile: if you git pull then run make build in the docker directory, it should work now, sorry for the inconvenience.

**Comment by JulianSMoore** [comment]
I'll try it all again tomorrow... if I can remember how ;) Thanks for taking the time to update stuff...
