### ISSUE TITLE
[CLARIFICATION] Chapter 16: An Encoder Decoder Network for Neural Machine Translation 

### ISSUE THREAD

**Issue by kasrahabib** [ageron/handson-ml2#537]
I had a look at this part of the book and read the following sentences:

“Note that the French translations are also used as inputs to the decoder, but shifted back by one step. In other words, the decoder is given as input the word that it should have output at the previous step (regardless of what it actually output).”

The question is, by “shifted back by one step” are you referring to the fact of adding   SOS at the beginning of each sentence?

- If no, then I am missing something. 

- If yes, maybe you can come with some explicit sentence because by adding  SOS  at the beginning of the sentence. I feel that the sentence is shifted forward by one step, i.e., I am saying this because you said you are working on 3rd ed. 

This book is the best so far, I read it time to time and enjoy it.

Cheers,
Kasra

**Comment by ageron** [comment]
Hi @kasrahabib ,
I see your point, thanks for bringing it to my attention. Indeed, the decoder receives sos + the target sentence as input. In my mind, adding sos at the front of the sentence pushes the rest back by one step, but I can see how it's possible to see it differently, from the perspective of the decoder.
I'll clarify this in the 3rd edition, thanks again!
