### ISSUE TITLE
Install Docker on Mac

### ISSUE THREAD

**Issue by dfumento** [ageron/handson-ml2#55]
I tried to install the docker image on Mac, latest OS, 10.16.1

Followed instructions switching to docker directory and issuing the
make build

[....]

Downloading and Extracting Packages
sqlite-3.30.1 | 1.9 MB | ########## | 100%
cffi-1.13.1 | 224 KB | ########## | 100%
asn1crypto-1.2.0 | 162 KB | ########## | 100%
cryptography-2.8 | 612 KB | ########## | 100%
ca-certificates-2019 | 131 KB | ########## | 100%
openssl-1.1.1d | 3.7 MB | ########## | 100%
pip-19.3.1 | 1.9 MB | ########## | 100%
setuptools-41.6.0 | 652 KB | ########## | 100%
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
Removing intermediate container 8d784dabb7cf
---> feff143c8ef1
Step 4/20 : COPY docker/environment.yml /tmp/
ERROR: Service 'handson-ml2' failed to build: COPY failed: stat /var/lib/docker/tmp/docker-builder765996510/docker/environment.yml: no such file or directory
make: *** [build] Error 1

**Comment by ageron** [comment]
Hi @dfumento ,
Thanks for your feedback. I'll take a look at this asap, but in the meantime I think you can just copy the `environment.yml` file from the project root to the `docker` subdirectory and try running the `build` command again.
Sorry for the inconvenience.

**Comment by dfumento** [comment]
Thank you for the suggestion and fixing the docker file.

Now it can’t find the git-nbdiffdriver file.

I later got this error which I assume that you are fixing from your comment of JulianSMoore issue.


Step 15/20 : RUN git-nbdiffdriver config --enable --global
---> Running in 33725ba23cf4
/bin/sh: 1: git-nbdiffdriver: not found
ERROR: Service 'handson-ml2' failed to build: The command '/bin/sh -c git-nbdiffdriver config --enable --global' returned a non-zero code: 127
make: *** [build] Error 1

**Comment by ageron** [comment]
I fixed the Dockerfile: if you `git pull` then run `make build` in the `docker` directory, it should work now, sorry for the inconvenience.

**Comment by dfumento** [comment]
Hi @ageron/handson-ml2<mailto:reply@reply.github.com>
I had originally tried to run docker without that statement.

XQuartz runs from the docker file.

I did a clean install of docker, deleting the /handson-ml2 directory and starting over.

TIA.

env.render()
---------------------------------------------------------------------------
NoSuchDisplayException                    Traceback (most recent call last)
<ipython-input-7-d9761596d5d9> in <module>
----> 1 env.render()

/opt/conda/envs/tf2/lib/python3.7/site-packages/gym/core.py in render(self, mode, **kwargs)
    231
    232     def render(self, mode='human', **kwargs):
--> 233         return self.env.render(mode, **kwargs)
    234
    235     def close(self):

/opt/conda/envs/tf2/lib/python3.7/site-packages/gym/envs/classic_control/cartpole.py in render(self, mode)
    148
    149         if self.viewer is None:
--> 150             from gym.envs.classic_control import rendering
    151             self.viewer = rendering.Viewer(screen_width, screen_height)
    152             l,r,t,b = -cartwidth/2, cartwidth/2, cartheight/2, -cartheight/2

/opt/conda/envs/tf2/lib/python3.7/site-packages/gym/envs/classic_control/rendering.py in <module>
     25
     26 try:
---> 27     from pyglet.gl import *
     28 except ImportError as e:
     29     raise ImportError('''

/opt/conda/envs/tf2/lib/python3.7/site-packages/pyglet/gl/__init__.py in <module>
    237     # trickery is for circular import
    238     _pyglet.gl = _sys.modules[__name__]
--> 239     import pyglet.window

/opt/conda/envs/tf2/lib/python3.7/site-packages/pyglet/window/__init__.py in <module>
   1894 if not _is_pyglet_docgen:
   1895     pyglet.window = sys.modules[__name__]
-> 1896     gl._create_shadow_window()
   1897

/opt/conda/envs/tf2/lib/python3.7/site-packages/pyglet/gl/__init__.py in _create_shadow_window()
    206
    207     from pyglet.window import Window
--> 208     _shadow_window = Window(width=1, height=1, visible=False)
    209     _shadow_window.switch_to()
    210

/opt/conda/envs/tf2/lib/python3.7/site-packages/pyglet/window/xlib/__init__.py in __init__(self, *args, **kwargs)
    164                     self._event_handlers[message] = func
    165
--> 166         super(XlibWindow, self).__init__(*args, **kwargs)
    167
    168         global _can_detect_autorepeat

/opt/conda/envs/tf2/lib/python3.7/site-packages/pyglet/window/__init__.py in __init__(self, width, height, caption, resizable, style, fullscreen, visible, vsync, display, screen, config, context, mode)
    499
    500         if not display:
--> 501             display = get_platform().get_default_display()
    502
    503         if not screen:

/opt/conda/envs/tf2/lib/python3.7/site-packages/pyglet/window/__init__.py in get_default_display(self)
   1843         :rtype: `Display`
   1844         """
-> 1845         return pyglet.canvas.get_display()
   1846
   1847 if _is_pyglet_docgen:

/opt/conda/envs/tf2/lib/python3.7/site-packages/pyglet/canvas/__init__.py in get_display()
     80
     81     # Otherwise, create a new display and return it.
---> 82     return Display()
     83
     84 if _is_pyglet_docgen:

/opt/conda/envs/tf2/lib/python3.7/site-packages/pyglet/canvas/xlib.py in __init__(self, name, x_screen)
     84         self._display = xlib.XOpenDisplay(name)
     85         if not self._display:
---> 86             raise NoSuchDisplayException('Cannot connect to "%s"' % name)
     87
     88         screen_count = xlib.XScreenCount(self._display)

NoSuchDisplayException: Cannot connect to "None"
