### ISSUE TITLE
Chapter 11, OneCycleScheduler

### ISSUE THREAD

**Issue by Jiaweihu08** [ageron/handson-ml2#56]
Shouldn't the **__interpolate_** function in the **_OneCycleScheduler_** class be returning
(rate2 - rate1) * **(self.iteration - iter1)** / (iter2 - iter1)
instead of 
(rate2 - rate1) * **(iter2 - self.iteration)** / (iter2 - iter1)
?

**Comment by ageron** [comment]
Great catch, thanks @Jiaweihu08 ! Just fixed this.
