### ISSUE TITLE
[BUG]chapter14 Unable to render code block

### ISSUE THREAD

**Issue by Monssica** [ageron/handson-ml2#566]
chapter14 can't open

**Comment by Monssica** [comment]
when use Tensorflow Datasets to load flower datasets,
ModuleNotFoundError: No module named 'tensorflow_datasets'

**Comment by ageron** [comment]
Hi @Monssica ,

I just tried [opening it on Colab](https://colab.research.google.com/github/ageron/handson-ml2/blob/master/14_deep_computer_vision_with_cnns.ipynb), there was no issue.

Could you please provide more details? Where are you trying to open the Jupyter notebook for chapter 14? Locally on your machine? By clicking on the notebook on github? In Colab?

If you tried clicking on the notebook on github, then this uses Github's notebook viewer, which is really not great: it often drops half the notebook (for long notebooks), or fails to open entirely (sometimes retrying works), and it doesn't display some equations correctly. I recommend opening the notebooks using Colab instead. For this, please visit: https://colab.research.google.com/github/ageron/handson-ml2/ and click on the notebook you want to open.

Hope this helps.
