### ISSUE TITLE
Ch 18 on Mac / Docker

### ISSUE THREAD

**Issue by dfumento** [ageron/handson-ml2#57]
Mac OS 10.15.1.    I have this error.
XQuartz 2.7.11

XQuartz is in the path of the docker file.

I installed this file as instructed:

```
python3 -m pip install -U pyvirtualdisplay
```

```python
try:
    import pyvirtualdisplay
    display = pyvirtualdisplay.Display(visible=0, size=(1400, 900)).start()
except ImportError:
    pass
```
```
xdpyinfo was not found, X start can not be checked! Please install xdpyinfo!

env.render()

---------------------------------------------------------------------------
NoSuchDisplayException                    Traceback (most recent call last)
<ipython-input-6-d9761596d5d9> in <module>
----> 1 env.render()

/opt/conda/envs/tf2/lib/python3.7/site-packages/gym/core.py in render(self, mode, **kwargs)
    231 
    232     def render(self, mode='human', **kwargs):
--> 233         return self.env.render(mode, **kwargs)
    234 
    235     def close(self):

/opt/conda/envs/tf2/lib/python3.7/site-packages/gym/envs/classic_control/cartpole.py in render(self, mode)
    148 
    149         if self.viewer is None:
--> 150             from gym.envs.classic_control import rendering
    151             self.viewer = rendering.Viewer(screen_width, screen_height)
    152             l,r,t,b = -cartwidth/2, cartwidth/2, cartheight/2, -cartheight/2

/opt/conda/envs/tf2/lib/python3.7/site-packages/gym/envs/classic_control/rendering.py in <module>
     25 
     26 try:
---> 27     from pyglet.gl import *
     28 except ImportError as e:
     29     raise ImportError('''

/opt/conda/envs/tf2/lib/python3.7/site-packages/pyglet/gl/__init__.py in <module>
    237     # trickery is for circular import
    238     _pyglet.gl = _sys.modules[__name__]
--> 239     import pyglet.window

/opt/conda/envs/tf2/lib/python3.7/site-packages/pyglet/window/__init__.py in <module>
   1894 if not _is_pyglet_docgen:
   1895     pyglet.window = sys.modules[__name__]
-> 1896     gl._create_shadow_window()
   1897 

/opt/conda/envs/tf2/lib/python3.7/site-packages/pyglet/gl/__init__.py in _create_shadow_window()
    206 
    207     from pyglet.window import Window
--> 208     _shadow_window = Window(width=1, height=1, visible=False)
    209     _shadow_window.switch_to()
    210 

/opt/conda/envs/tf2/lib/python3.7/site-packages/pyglet/window/xlib/__init__.py in __init__(self, *args, **kwargs)
    164                     self._event_handlers[message] = func
    165 
--> 166         super(XlibWindow, self).__init__(*args, **kwargs)
    167 
    168         global _can_detect_autorepeat

/opt/conda/envs/tf2/lib/python3.7/site-packages/pyglet/window/__init__.py in __init__(self, width, height, caption, resizable, style, fullscreen, visible, vsync, display, screen, config, context, mode)
    499 
    500         if not display:
--> 501             display = get_platform().get_default_display()
    502 
    503         if not screen:

/opt/conda/envs/tf2/lib/python3.7/site-packages/pyglet/window/__init__.py in get_default_display(self)
   1843         :rtype: `Display`
   1844         """
-> 1845         return pyglet.canvas.get_display()
   1846 
   1847 if _is_pyglet_docgen:

/opt/conda/envs/tf2/lib/python3.7/site-packages/pyglet/canvas/__init__.py in get_display()
     80 
     81     # Otherwise, create a new display and return it.
---> 82     return Display()
     83 
     84 if _is_pyglet_docgen:

/opt/conda/envs/tf2/lib/python3.7/site-packages/pyglet/canvas/xlib.py in __init__(self, name, x_screen)
     84         self._display = xlib.XOpenDisplay(name)
     85         if not self._display:
---> 86             raise NoSuchDisplayException('Cannot connect to "%s"' % name)
     87 
     88         screen_count = xlib.XScreenCount(self._display)

NoSuchDisplayException: Cannot connect to "None"
```

**Comment by ageron** [comment]
Hi @dfumento,

Thanks for your question. The pyvirtualdisplay package is only needed on a headless server, i.e., a machine without a screen, such as on a VM or when using Colab. I suggest you uninstall pyvirtualdisplay so the import will raise an exception which will be caught and ignored. The rest should work fine.

Hope this helps,
Aurélien

**Comment by dfumento** [comment]
I had originally tried to run docker without that statement.
 
XQuartz runs from the docker file.
 
I did a clean install of docker, deleting the /handson-ml2 directory and starting over.
 
TIA.
 
env.render()
---------------------------------------------------------------------------
NoSuchDisplayException                    Traceback (most recent call last)
<ipython-input-7-d9761596d5d9> in <module>
----> 1 env.render()
 
/opt/conda/envs/tf2/lib/python3.7/site-packages/gym/core.py in render(self, mode, **kwargs)
    231
    232     def render(self, mode='human', **kwargs):
--> 233         return self.env.render(mode, **kwargs)
    234
    235     def close(self):
 
/opt/conda/envs/tf2/lib/python3.7/site-packages/gym/envs/classic_control/cartpole.py in render(self, mode)
    148
    149         if self.viewer is None:
--> 150             from gym.envs.classic_control import rendering
    151             self.viewer = rendering.Viewer(screen_width, screen_height)
    152             l,r,t,b = -cartwidth/2, cartwidth/2, cartheight/2, -cartheight/2
 
/opt/conda/envs/tf2/lib/python3.7/site-packages/gym/envs/classic_control/rendering.py in <module>
     25
     26 try:
---> 27     from pyglet.gl import *
     28 except ImportError as e:
     29     raise ImportError('''
 
/opt/conda/envs/tf2/lib/python3.7/site-packages/pyglet/gl/__init__.py in <module>
    237     # trickery is for circular import
    238     _pyglet.gl = _sys.modules[__name__]
--> 239     import pyglet.window
 
/opt/conda/envs/tf2/lib/python3.7/site-packages/pyglet/window/__init__.py in <module>
   1894 if not _is_pyglet_docgen:
   1895     pyglet.window = sys.modules[__name__]
-> 1896     gl._create_shadow_window()
   1897
 
/opt/conda/envs/tf2/lib/python3.7/site-packages/pyglet/gl/__init__.py in _create_shadow_window()
    206
    207     from pyglet.window import Window
--> 208     _shadow_window = Window(width=1, height=1, visible=False)
    209     _shadow_window.switch_to()
    210
 
/opt/conda/envs/tf2/lib/python3.7/site-packages/pyglet/window/xlib/__init__.py in __init__(self, *args, **kwargs)
    164                     self._event_handlers[message] = func
    165
--> 166         super(XlibWindow, self).__init__(*args, **kwargs)
    167
    168         global _can_detect_autorepeat
 
/opt/conda/envs/tf2/lib/python3.7/site-packages/pyglet/window/__init__.py in __init__(self, width, height, caption, resizable, style, fullscreen, visible, vsync, display, screen, config, context, mode)
    499
    500         if not display:
--> 501             display = get_platform().get_default_display()
    502
    503         if not screen:
 
/opt/conda/envs/tf2/lib/python3.7/site-packages/pyglet/window/__init__.py in get_default_display(self)
   1843         :rtype: `Display`
   1844         """
-> 1845         return pyglet.canvas.get_display()
   1846
   1847 if _is_pyglet_docgen:
 
/opt/conda/envs/tf2/lib/python3.7/site-packages/pyglet/canvas/__init__.py in get_display()
     80
     81     # Otherwise, create a new display and return it.
---> 82     return Display()
     83
     84 if _is_pyglet_docgen:
 
/opt/conda/envs/tf2/lib/python3.7/site-packages/pyglet/canvas/xlib.py in __init__(self, name, x_screen)
     84         self._display = xlib.XOpenDisplay(name)
     85         if not self._display:
---> 86             raise NoSuchDisplayException('Cannot connect to "%s"' % name)
     87
     88         screen_count = xlib.XScreenCount(self._display)
 
NoSuchDisplayException: Cannot connect to "None"

**Comment by ageron** [comment]
Hi @dfumento ,
I'm really sorry for the installation issues. I fixed the `Dockerfile` 5 days ago. Could you please `git pull` the latest version and try running `make build` then `make run`, and try again? I just tested on my MacBook (10.14.6) and it worked fine, no error with `env.render()`.
Hope this helps.

**Comment by dfumento** [comment]
When you updated the docker image 5 days ago, I deleted the entire cloned directory and recloned the entire directory and did the build from scratch which is how I got the error I reported.  I did the process again with the same outcome.  Under Mac OS Catalina, 15.1, bash is no longer the default shell, zsh now is.  I noticed that ~/handson_ml2/docker/bin was not in my path and I added it this time, but still have the same error.


env.render()
---------------------------------------------------------------------------
NoSuchDisplayException                    Traceback (most recent call last)
<ipython-input-7-d9761596d5d9> in <module>
----> 1 env.render()

/opt/conda/envs/tf2/lib/python3.7/site-packages/gym/core.py in render(self, mode, **kwargs)
    231 
    232     def render(self, mode='human', **kwargs):
--> 233         return self.env.render(mode, **kwargs)
    234 
    235     def close(self):

/opt/conda/envs/tf2/lib/python3.7/site-packages/gym/envs/classic_control/cartpole.py in render(self, mode)
    148 
    149         if self.viewer is None:
--> 150             from gym.envs.classic_control import rendering
    151             self.viewer = rendering.Viewer(screen_width, screen_height)
    152             l,r,t,b = -cartwidth/2, cartwidth/2, cartheight/2, -cartheight/2

/opt/conda/envs/tf2/lib/python3.7/site-packages/gym/envs/classic_control/rendering.py in <module>
     25 
     26 try:
---> 27     from pyglet.gl import *
     28 except ImportError as e:
     29     raise ImportError('''

/opt/conda/envs/tf2/lib/python3.7/site-packages/pyglet/gl/__init__.py in <module>
    237     # trickery is for circular import
    238     _pyglet.gl = _sys.modules[__name__]
--> 239     import pyglet.window

/opt/conda/envs/tf2/lib/python3.7/site-packages/pyglet/window/__init__.py in <module>
   1894 if not _is_pyglet_docgen:
   1895     pyglet.window = sys.modules[__name__]
-> 1896     gl._create_shadow_window()
   1897 

/opt/conda/envs/tf2/lib/python3.7/site-packages/pyglet/gl/__init__.py in _create_shadow_window()
    206 
    207     from pyglet.window import Window
--> 208     _shadow_window = Window(width=1, height=1, visible=False)
    209     _shadow_window.switch_to()
    210 

/opt/conda/envs/tf2/lib/python3.7/site-packages/pyglet/window/xlib/__init__.py in __init__(self, *args, **kwargs)
    164                     self._event_handlers[message] = func
    165 
--> 166         super(XlibWindow, self).__init__(*args, **kwargs)
    167 
    168         global _can_detect_autorepeat

/opt/conda/envs/tf2/lib/python3.7/site-packages/pyglet/window/__init__.py in __init__(self, width, height, caption, resizable, style, fullscreen, visible, vsync, display, screen, config, context, mode)
    499 
    500         if not display:
--> 501             display = get_platform().get_default_display()
    502 
    503         if not screen:

/opt/conda/envs/tf2/lib/python3.7/site-packages/pyglet/window/__init__.py in get_default_display(self)
   1843         :rtype: `Display`
   1844         """
-> 1845         return pyglet.canvas.get_display()
   1846 
   1847 if _is_pyglet_docgen:

/opt/conda/envs/tf2/lib/python3.7/site-packages/pyglet/canvas/__init__.py in get_display()
     80 
     81     # Otherwise, create a new display and return it.
---> 82     return Display()
     83 
     84 if _is_pyglet_docgen:

/opt/conda/envs/tf2/lib/python3.7/site-packages/pyglet/canvas/xlib.py in __init__(self, name, x_screen)
     84         self._display = xlib.XOpenDisplay(name)
     85         if not self._display:
---> 86             raise NoSuchDisplayException('Cannot connect to "%s"' % name)
     87 
     88         screen_count = xlib.XScreenCount(self._display)

NoSuchDisplayException: Cannot connect to "None"

**Comment by ageron** [comment]
Hi dfumento,
Thanks for your feedback. I tried deleting everything and starting from scratch, and everything works fine for me, so unfortunately I can't reproduce the issue you are getting. I'll try upgrading to Catalina, perhaps I'll run into the issue then. I'll keep you posted.

**Comment by dfumento** [comment]
Hi ageron,
Thank you for the help.  The Mac OS was freshly installed from zeroed disk in July.  Python installed with Anaconda.

I have trouble both with the docker install and the Mac native install in the separate environment, issue #54 which causes problems when trying to import numpy (1 statement), from Jupyter notebook, even though importing numpy with iPython in the env. works ok.

**Comment by ageron** [comment]
I installed Catalina, and I ran the following commands:

```bash
conda activate base
conda update --all
git clone https://github.com/ageron/handson-ml2.git
cd handson-ml2
conda env create -f environment.yml --name tf2test
conda activate tf2test
ipython kernel install --name "tf2test" --user
jupyter notebook
```

Then I opened a notebook in Jupyter and I selected the tf2test kernel, and everything worked fine. 👍 

Could you please try running these commands?

**Comment by dfumento** [comment]
Those steps worked, thank you.  I had tried the pip procedures -- your documentation said that conda didn't yet have the TF v2.

I ran though all of Chapter 18 on RL.
Also, one step [36?] went extremely slowly using only one thread with 100% running python.  I got about 80 iterations and then had to quit and resume at the next cell.

I'm running on a mid-2015 15" MacBook Pro.

This is the beginning of the code.

env = gym.make("CartPole-v1")
env.seed(42);

for iteration in range(n_iterations):
    all_rewards, all_grads = play_multiple_episodes(
        env, n_episodes_per_update, n_max_steps, model, loss_fn)
    total_rewards = sum(map(sum, all_rewards))                     # Not shown in the book
    print("\rIteration: {}, mean rewards: {:.1f}".format(          # Not shown
        iteration, total_rewards / n_episodes_per_update), end="") # Not shown
    all_final_rewards = discount_and_normalize_rewards(all_rewards,
                                                       discount_rate)


Also, step [117] ?? 
train_agent(n_iterations=10000)

Required 10 or more mins using 5 threads I think.


I am not certain if these steps are supposed to take this long or not.

Thank you for helping out.

**Comment by ageron** [comment]
Great, thanks for your feedback, and I'm glad it finally worked! Yes, this RL notebook is the slowest of all the notebooks. You'll need to use a GPU and have plenty of RAM. One option is to use a cloud VM, for example on Google Cloud. It will cost you a bit of cash, depending on the VM specs and the GPU you select, but it will run _much_ faster.
