### ISSUE TITLE
urllib not defined

### ISSUE THREAD

**Issue by truvaking** [ageron/handson-ml2#58]
Hello,

Sorry I'm not a Python expert, in `01_the_machine_learning_landscape` there is an error in this cell :

```python
# Download the data
DOWNLOAD_ROOT = "https://raw.githubusercontent.com/ageron/handson-ml2/master/"
os.makedirs(datapath, exist_ok=True)
for filename in ("oecd_bli_2015.csv", "gdp_per_capita.csv"):
    print("Downloading", filename)
    url = DOWNLOAD_ROOT + "datasets/lifesat/" + filename
    urllib.request.urlretrieve(url, datapath + filename)
```

 the `import urllib` is missing

**Comment by ageron** [comment]
Hi @truvaking ,
My apologies, I forgot the import statement. @SublimeApple just submitted a PR #59 to fix this.
You just need to add `import urllib` at the beginning of the cell or pull the latest version of the notebook.
Cheers.
