### ISSUE TITLE
[QUESTION] Anaconda Env

### ISSUE THREAD

**Issue by AKllX** [ageron/handson-ml2#602]
Hi!

Today I tried to setup the test notebooks on my own computer. I'm running a Ubuntu 22.04 (Jimmy) installed only for this course on a hardware-compatible machine (not virtualized).

However, when I try to build the Anaconda environment it seems to keep stucking at 'Solving environmnet'. 

The command I ran is _conda env create -f environment.yml_ and my environment.yml is exactly the one online.
I've followed all the previous steps: Installed Anaconda, the GPU driver (GTX 1660TI), CUDA and cuDNN.

I also tried to force the conda env to strict mode. Then it ran and checked for conflicts of dependencies. In the end it fails because it encountered some conflicts that it wasn't able to fix. 

Is there any suggestions to fix that? I read some people online talking about using mamba instead. Is it possible? Thank you in advance.

**Comment by sven-olding** [comment]
Same issue here…

**Comment by qLag** [comment]
Same :'(

**Comment by qLag** [comment]
> Same :'(

Actually it worked after waiting 1-2 hours.
Tip: I enabled full verbose mode with the -vv option to track progress, it's more comfortable!

**Comment by sven-olding** [comment]
I could get it working somehow after googling around a bit. I've tried this 
```
conda config --set channel_priority strict
```
in combination with moving the python dependecy to the top of the environment.yml
```
name: tf2
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8  # Python! Not using latest version as some libs lack support
  - box2d-py  # used only in chapter 18, exercise 8
  - ftfy=6.0  # used only in chapter 16 by the transformers library
...
```
Not sure if this will help, I've tried a couple of other tips from Stackoverflow and other sources but that was the last thing I did and afterwards it worked

**Comment by ageron** [comment]
Thanks everyone. I'll try the changes recommended by @sven-olding . I do not have a Windows machine, which makes testing this a bit trickier (I need to use a Windows VM on Google Cloud, which takes time to setup), so your feedback is much appreciated. 👍

**Comment by AKllX** [comment]
Thank you for the help guys! Mine also worked after I left it unattended through the night. The process does work but It does take a long time.

**Comment by ageron** [comment]
Btw, Anaconda's documentation has an interesting page on [how to improve `conda`'s performance](https://docs.conda.io/projects/conda/en/latest/user-guide/concepts/conda-performance.html).
