### ISSUE TITLE
tensorflow-gpu 2.0.0 and cuda 10.1

### ISSUE THREAD

**Issue by JoshLikesBeer** [ageron/handson-ml2#61]
The tensorflow-gpu 2.0.0 you get from pip only works with cuda 10.0. If you have the newer cuda 10.1 installed, you'll either have to downgrade cuda or compile tensorflow from source yourself.

I went the latter route and it works fine with cuda 10.1.

**Comment by ageron** [comment]
Thanks for your feedback! Indeed, I should probably add a comment about this in the book. Unfortunately, these versions change so frequently, it's hard to keep track.

**Comment by ageron** [comment]
The simplest option is probably to use Anaconda.

```bash
conda install tensorflow-gpu
```

This will always install the right version of CUDA.
