### ISSUE TITLE
Chapter 19 tensorflow_serving_deploying_Problem

### ISSUE THREAD

**Issue by klyuhang9** [ageron/handson-ml2#64]
In Exporting SavedModels part, the code: (that is on this book2th)

```python
saved_model = tf.saved_model.load(model_path)
inputs = keras.layers.Input(shape=...)
outputs = saved_model(inputs, training=False)
model = keras.models.Model(inputs=[inputs], outputs=[outputs])
```

The error appear: 

```
"tensors, but found {}".format(keras_symbolic_tensors))
tensorflow.python.eager.core._SymbolicException: Inputs to eager execution function cannot be Keras symbolic tensors, but found [<tf.Tensor 'input_1:0' shape=(None, 28, 28, 1) dtype=float32>]
```

I don't know how to solve this problem even after searching online. Thanks for your help.

**Comment by ageron** [comment]
Hi @klyuhang9 ,

Thanks for your feedback. It seems that the TensorFlow team has simplified loading SavedModels into Keras models: now you just need to run `tf.keras.models.load_model(model_path)`!

Here's a small [Colab notebook](https://colab.research.google.com/drive/1WODSCGOIpmjlkR_hGR9361jNd-KEhf6L) to demonstrate this.

I also noticed that it's no longer necessary to specify `training=False`.

I'll update the book and the notebook.

Hope this helps!

**Comment by klyuhang9** [comment]
@ageron 
Thanks, the problem solved by the way you mentioned.
By the way, I may find that （also in this section) "install tensorflow-serving-api" is suitable for the virtual environment that installed tensorflow-cpu; If the virtual environment that installed tensorflow-gpu, we need to install  "tensorflow-serving-api-gpu", otherwise the former will affect the use of GPU to run programs on tensorflow.

**Comment by ageron** [comment]
Great, I'm glad this solved the problem.
Thanks for your feedback regarding the CPU/GPU problem, I'll look into it.
Note that starting in TF 2.1 (and in TF 1.15, but not in TF 2.0), `pip install tensorflow` will install a version of TensorFlow that supports both CPU and GPU: it will first look for a GPU, and if it does not find one, it will fallback to CPU. If you need a smaller installation footprint and you don't care about GPU, then you can install `pip install tensorflow-cpu` which only supports CPU.
I'm guessing that the same will be true with `tensorflow-serving-api`.
Hope this helps.
