### ISSUE TITLE
Chapter 10 save mode and reload it failure

### ISSUE THREAD

**Issue by ycbq999** [ageron/handson-ml2#67]
The exact code I run on my PC give me error like this:

```python
model = keras.models.load_model("my_keras_model.h5")
```
```
Traceback (most recent call last):

  File "<ipython-input-100-7fe8f1e1ad2a>", line 1, in <module>
    model = keras.models.load_model("my_keras_model.h5")

  File "C:\Users\ycbq9\.conda\envs\tf\lib\site-packages\tensorflow_core\python\keras\saving\save.py", line 145, in load_model
    isinstance(filepath, h5py.File) or h5py.is_hdf5(filepath))):

  File "C:\Users\ycbq9\.conda\envs\tf\lib\site-packages\h5py\_hl\base.py", line 44, in is_hdf5
    return h5f.is_hdf5(filename_encode(fname))

  File "C:\Users\ycbq9\.conda\envs\tf\lib\site-packages\h5py\_hl\compat.py", line 114, in filename_encode
    return filename.encode(WINDOWS_ENCODING, "strict")

UnicodeEncodeError: 'mbcs' codec can't encode characters in position 0--1: invalid character
```

I am not sure how to check the encode error. If you can help please. Thanks

**Comment by ageron** [comment]
Hi @ycbq999,

Thanks for your question. It looks like the filename cannot be encoded using Windows's MCBS encoding. If the filename is `"my_keras_model.h5"`, then something is very wrong, since this looks like 100% ASCII characters to me, so it should really work. Perhaps the filename contains some invisible characters that cannot be encoded. This can sometimes happen when typing some key combinations by accident. So I suggest deleting entirely the filename `"my_keras_model.h5"` (in case it contains invisible characters), then typing it again carefully. Alternatively, this issue sometimes happen when typing a single `\` in a Windows path instead of double `\\`:

```python
filename = "C:\\some\\path\\to\\handson-ml2\\my_keras_model.h5"  # GOOD
filename = r"C:\some\path\to\handson-ml2\my_keras_model.h5"  # Also GOOD using r prefix
filename = "C:\some\path\to\handson-ml2\my_keras_model.h5"  # BAD
```

Hope this helps.

**Comment by ycbq999** [comment]
> Hi @ycbq999,
> 
> Thanks for your question. It looks like the filename cannot be encoded using Windows's MCBS encoding. If the filename is `"my_keras_model.h5"`, then something is very wrong, since this looks like 100% ASCII characters to me, so it should really work. Perhaps the filename contains some invisible characters that cannot be encoded. This can sometimes happen when typing some key combinations by accident. So I suggest deleting entirely the filename `"my_keras_model.h5"` (in case it contains invisible characters), then typing it again carefully. Alternatively, this issue sometimes happen when typing a single `\` in a Windows path instead of double `\\`:
> 
> ```python
> filename = "C:\\some\\path\\to\\handson-ml2\\my_keras_model.h5"  # GOOD
> filename = r"C:\some\path\to\handson-ml2\my_keras_model.h5"  # Also GOOD using r prefix
> filename = "C:\some\path\to\handson-ml2\my_keras_model.h5"  # BAD
> ```
> 
> Hope this helps.

Thanks. It really helps. I save to another folder without confusing path name. and it worked

**Comment by ageron** [comment]
I'm glad it worked! If you can share this information, could you please copy/paste the pathname that failed, in case others run into a similar issue?
Thanks!

**Comment by ycbq999** [comment]
Sure!
C:\Users\ycbq9\OneDrive\桌面\Machine Learning-20190802T072557Z-001\Machine Learning\handson-ml-master\Version 2 Hands on ML\handson-ml2-master\handson-ml2-
