### ISSUE TITLE
Chapter2 - select and train a model

### ISSUE THREAD

**Issue by ShaoboZhang** [ageron/handson-ml2#71]
When I try to run the code on my pc, I found that the rmse of linear model and its standard deviation under cross validation are both rather small (about 1e-10).
And for the model of decision tree, its standard deviation  is about 70.

For these 2 models, the performance is much better than it did on the book. Only for the model of random forest, it has a similar performance.

I'm wondering if anyone meets the same issue and curious about why this happened.
![model perfomances](https://user-images.githubusercontent.com/16928436/69634964-54a94000-108e-11ea-88f7-dcf3938d1afa.png)

**Comment by laorencel** [comment]
###
