### ISSUE TITLE
conda install misses tensorflow-metadata and tensorflow-addons

### ISSUE THREAD

**Issue by aseedb** [ageron/handson-ml2#74]
When installing conda environment I got an error: 

```
ResolvePackageNotFound: 
  - tensorflow-metadata=0.15.1
  - tensorflow-addons=0.6.0
```
I edited environment.yml and moved these two packages under pip.
then conda env create ran without error. However pip install part uninstalled some packages and reinstalled another version of them. See log file below. 
I can activate tf2 environment without error. I have not tried yet to run any notebook.

[install.log](https://github.com/ageron/handson-ml2/files/3966422/install.log)

**Comment by ageron** [comment]
Hi @aseedb ,
Thanks for your feedback. I updated environment.yml recently, and I made a couple mistakes, sorry about that. I just fixed this, it should work now.
Hope this helps.
