### ISSUE TITLE
[may I ask] (Chapter 3) a very bumpy precision curve

### ISSUE THREAD

**Issue by hopezh** [ageron/handson-ml2#78]
Dear Aurélien, I'm following your code for **Chapter 3** to **plot the precision and recall vs threshold curve** as shown in **line [36]** of [your jupyter notebook](https://github.com/ageron/handson-ml2/blob/master/03_classification.ipynb). 

I understand that my output may not be exactly the same as yours, but the top-right part of the precision curve I plotted is **"wildly" bumpy** as compared to yours as shown below.

May I ask if this indicate that there are errors in my code while replicating yours? 
Or, this could be possible for different run of the same data set? 

My jupyter notebook is shown [here](https://github.com/hopezh/learn_hands_on_ML_v2/blob/master/ch3_classification_v2.ipynb). 

Thank you. 

![Screenshot 2019-12-29 at 16 37 11](https://user-images.githubusercontent.com/23435810/71554448-22f31280-2a5a-11ea-898e-48184062e59d.png)

**Comment by EricThomson** [comment]
@hopezh my precision curve looks like yours. Even more than the zig-zags, I worry about the more qualitative difference that they don't intersect at threshold = 0.

**Comment by hopezh** [comment]
@EricThomson Thanks for your reply. 

I'm not aware that the two curves are to be intersecting at the position where threshold=0. 

May I ask if you can point me to some reference to learn more about it?

**Comment by EricThomson** [comment]
@hopezh I searched some yesterday and couldn't find anything on that. Now that I've read the rest of the chapter I'm now thinking that my intuition was just flat-out wrong, that result was a coincidence.  For instance, I just re-ran things with `random_state = 20` and they intersect a little above zero. So my intuition seems misplaced, it seems just a noisy thing. 

Also, in practice people typically just focus on precision-recall curves (Figure 3-5 in the book), so I will probably focus on building intuitions about those for evaluating classifiers (and ROC curves, which in my field are the most standard tool).

**Comment by VirajVaitha123** [comment]
Hi both,

There is two possible reasons I can think off. 

The first is the random_state argument. If you open his github notebook on the topic and see if you've replicated the model exactly the same.. It may differ slightly from the book.

Secondly, their are two ways to access the Mnist dataset. There is a chance you used load_digits() and not fetchml?

One produces digits that are 8x8 and the other is much larger something like 28x28

Hope this helps

**Comment by mauricio-ms** [comment]
I having the same results in the same bumpy precision curve in the plot.

**Comment by anoldmaninthesea** [comment]
I also get the same bumpy precision curve. We may not be using the same dataset the author used at the time... Maybe there were some updates/changes to the data.

**Comment by mauricio-ms** [comment]
Installing the sklearn version 0.20.0 resolve all the problems, I get the same results as the book in the entire notebook.

**Comment by ageron** [comment]
Sorry for the long silence, I've been busy moving to New Zealand, but with the lockdown I now have some time to unpile all the pending issues. As @EricThomson guessed and @mauricio-ms demonstrated, the latest Scikit-Learn made some internal changes so the results are not exactly the same as in the book. Same for TensorFlow by the way (in version 2.1, they entirely changed the way random numbers are generated). So you should not expect things to be exactly the same, but hopefully they'll be in the same ballpark.
