### ISSUE TITLE
Where is Appendix A?

### ISSUE THREAD

**Issue by gkd720** [ageron/handson-ml2#8]
Excellent book. I'm going through chapter 4 exercises, and was trying to check my answers. The notebook says to look in Appendix A, but I can't find it going through all the directories. Is it available yet? Did I miss it? Thanks.

**Comment by ageron** [comment]
Hi @gkd720 ,
It is not available in the early release yet, as I have not updated it yet for the 2nd edition. It's on my To-Do list pretty soon though.

**Comment by sidbhat1979** [comment]
Hi Ageron, Just checking if the appendix A is released. Will be good to have it. thanks.

**Comment by ageron** [comment]
Sorry for the late response. Appendix A is finished and in the book now.
