### ISSUE TITLE
Chapter 18 - soft update in Double DQN

### ISSUE THREAD

**Issue by lytkarinskiy** [ageron/handson-ml2#89]
Hi, first of all thanks for this amazing book!

I think there is an error in commented section in cell 68 of 18_reinforcement_learning.ipynb:

It says actually that we don't change weights at all:
```python
# Alternatively, you can do soft updates at each step:
if episode > 50:
    target_weights = target.get_weights()
    online_weights = model.get_weights()
    for index in range(len(target_weights)):
        target_weights[index] = 0.99 * target_weights[index] + 0.01 * target_weights[index]
    target.set_weights(target_weights)
```

But we should keep most of target_weights and a little of online weights, so it should be

```python
# Alternatively, you can do soft updates at each step:
if episode > 50:
    target_weights = target.get_weights()
    online_weights = model.get_weights()
    for index in range(len(target_weights)):
        target_weights[index] = 0.99 *target_weights[index] + 0.01 * online_weights[index]
    target.set_weights(target_weights)
```

**Comment by ageron** [comment]
Hi @lytkarinskiy ,
Thanks a lot for your great feedback, and sorry for the late response. You're absolutely right of course. That's the problem with commented-out code: they're often not very well tested! ;-)
I'll fix this right away.
Thanks again.
