### ISSUE TITLE
huber_fn in Chapter 12

### ISSUE THREAD

**Issue by aslanismailgit** [ageron/handson-ml2#94]
Aurelien,

I have been playing with the huber_fn in Chapter 12.

When (y_pred=1, y_true=1) or both integer
then it gives a type error. 

So changed below line in my script:
    new	    	: error = tf.cast((y_true - y_pred),tf.float32)
    old one	: error = y_true - y_pred

This only happens when you try a single set of value as above.
if you start with a float, tf automatically sets its type
as dtype=float32. I mean, In cell 62 while drawing the plot, I changed z[125]=1,
no error comes out. 
I doubt that,  if z were all int, then the same error would show up.

By the way; 
Great work!
Congratulations!
Thanks!
ismail

**Comment by openerror** [comment]
I have a similar issue, but during training using HuberLoss subclassed from keras.metrics.Mean

![Untitled](https://user-images.githubusercontent.com/11012723/76385769-cfd1f180-631f-11ea-8870-a2d177b04da3.png)

Tensorflow assumes float32 by default but Numpy assumes float64. Wonder what's the best practice here? Casting all data to float32 before sending it to the neural network, maybe?

**Comment by ageron** [comment]
Thanks for your feedback.  Indeed, the types need to match, and both your solutions work fine. I prefer converting the data in NumPy, before passing it on to TensorFlow, for performance reasons: if the data is converted as early as possible, there's no need to cast it again and again during training. I'll fix the notebook (apparently TF used to be more tolerant, as this notebook used to work fine).

**Comment by openerror** [comment]
Thank you for sharing your practices and for fixing the notebook!
